'use strict';

module.exports = [
  {
    id: 'AWS-001',
    title: 'EC2 Instance Types Overview',
    domain: 'aws',
    content: 'EC2 instance families: t3/t3a (burstable, general purpose), m5/m6i (general purpose, steady-state), c5/c6i (compute-optimized), r5/r6i (memory-optimized), i3/i4i (storage-optimized), p4/g5 (GPU). t3.micro is free tier eligible. Use t3/t3a for dev/staging and low-traffic apps. Use m5/m6i for production web servers. Use r5 for databases and caches. Use c5 for CPU-intensive workloads. Graviton (t4g, m6g, c6g, r6g) offers 20-40% better price-performance.',
    bestPractice: 'Start with t3 for testing, rightsize after monitoring. Use Graviton (ARM) instances for 20-40% cost savings. Enable detailed monitoring. Use instance metadata service v2 (IMDSv2) for security.',
    tags: ['aws', 'ec2', 'instance-types', 'compute', 'graviton'],
  },
  {
    id: 'AWS-002',
    title: 'AWS IAM Least Privilege',
    domain: 'aws',
    content: 'IAM policies should grant minimum permissions needed. Use AWS managed policies as starting points, then create custom policies. Use IAM Access Analyzer to identify unused permissions. Avoid using root account. Enable MFA on all human users. Use IAM roles (not access keys) for EC2/ECS/Lambda. Use STS AssumeRole for cross-account access.',
    fix: 'Run IAM Access Analyzer to find overly permissive policies. Generate policies based on CloudTrail activity with Access Analyzer policy generation.',
    bestPractice: 'Never use root account for daily work. Enable MFA everywhere. Use IAM roles for services, not access keys. Implement SCPs in AWS Organizations. Review permissions quarterly. Use permission boundaries for delegated administration.',
    tags: ['aws', 'iam', 'security', 'least-privilege', 'access-control'],
  },
  {
    id: 'AWS-003',
    title: 'AWS VPC Design',
    domain: 'aws',
    content: 'A well-designed VPC: Use /16 CIDR (65,536 IPs). Create subnets across 3 AZs for high availability. Subnet tiers: public (ALB, NAT GW), private (app servers, containers), isolated (databases). Use NAT Gateway for private subnet internet access. VPC Flow Logs for network monitoring. VPC Endpoints for AWS service access without internet.',
    bestPractice: 'Plan CIDR ranges to avoid overlaps (important for VPC peering/Transit Gateway). Use /24 subnets minimum. Place databases in isolated subnets with no internet route. Use VPC endpoints for S3, DynamoDB, ECR to reduce NAT Gateway costs. Enable Flow Logs to S3 for security analysis.',
    tags: ['aws', 'vpc', 'networking', 'subnets', 'architecture'],
  },
  {
    id: 'AWS-004',
    title: 'AWS Security Groups vs NACLs',
    domain: 'aws',
    content: 'Security Groups (SG): Stateful (return traffic auto-allowed), instance-level, allow rules only, evaluated as a whole. NACLs: Stateless (must allow both inbound and outbound), subnet-level, allow and deny rules, evaluated in order. Use SGs as primary defense. Use NACLs for subnet-level blocking (e.g., block known bad IPs).',
    bestPractice: 'Use SGs for application-level rules. Reference other SGs instead of CIDR when possible (e.g., allow ALB SG to app SG). Use NACLs sparingly for subnet-level deny rules. Never allow 0.0.0.0/0 on database ports. Log denied connections with VPC Flow Logs.',
    tags: ['aws', 'security', 'security-groups', 'nacl', 'networking', 'firewall'],
  },
  {
    id: 'AWS-005',
    title: 'AWS RDS Best Practices',
    domain: 'aws',
    content: 'RDS managed database service supports PostgreSQL, MySQL, MariaDB, Oracle, SQL Server. Multi-AZ for high availability (synchronous replication, automatic failover). Read Replicas for read scaling (async replication). Enable automated backups (35-day retention). Use Parameter Groups for tuning. Enable Enhanced Monitoring and Performance Insights.',
    bestPractice: 'Always use Multi-AZ for production. Enable automated backups with 7+ day retention. Use Read Replicas for reporting queries. Use RDS Proxy for connection pooling (critical for Lambda). Enable encryption at rest and in transit. Use IAM authentication when possible.',
    tags: ['aws', 'rds', 'database', 'postgresql', 'mysql', 'high-availability'],
  },
  {
    id: 'AWS-006',
    title: 'AWS S3 Security and Policies',
    domain: 'aws',
    content: 'S3 bucket security: Block Public Access (enable at account level). Use bucket policies for cross-account access. Enable server-side encryption (SSE-S3 or SSE-KMS). Enable versioning for data protection. Use S3 Object Lock for compliance. Access logging to a separate bucket. Use VPC endpoints for private access.',
    fix: 'Enable S3 Block Public Access at account level: aws s3control put-public-access-block --account-id ACCOUNT_ID --public-access-block-configuration BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true',
    bestPractice: 'Enable versioning and lifecycle policies. Use S3 Intelligent-Tiering for unknown access patterns. Use S3 Glacier for archives. Enable access logging. Use presigned URLs for temporary access. Set up S3 Event Notifications for automation.',
    tags: ['aws', 's3', 'storage', 'security', 'encryption'],
  },
  {
    id: 'AWS-007',
    title: 'AWS ECS (Elastic Container Service)',
    domain: 'aws',
    content: 'ECS runs Docker containers on AWS. Two launch types: EC2 (you manage instances) and Fargate (serverless, AWS manages infrastructure). Components: Cluster, Service (desired count, load balancer), Task Definition (container specs), Task (running instance). Use Fargate for simplicity, EC2 for cost optimization at scale or GPU workloads.',
    bestPractice: 'Use Fargate for most workloads (simpler operations). Use ECS Exec for debugging (replaces SSH). Set task-level CPU/memory limits. Use awslogs log driver for CloudWatch integration. Use ECS Service Connect or App Mesh for service discovery. Enable Container Insights for monitoring.',
    tags: ['aws', 'ecs', 'containers', 'fargate', 'docker'],
  },
  {
    id: 'AWS-008',
    title: 'AWS EKS (Elastic Kubernetes Service)',
    domain: 'aws',
    content: 'EKS is managed Kubernetes on AWS. AWS manages the control plane. You manage worker nodes (EC2, Fargate, or managed node groups). Use managed node groups for simplest operation. Integrates with ALB Ingress Controller, IAM roles for service accounts (IRSA), EBS CSI driver, VPC CNI.',
    bestPractice: 'Use managed node groups with Bottlerocket OS. Enable IRSA (IAM Roles for Service Accounts) instead of node-level IAM roles. Use Karpenter for intelligent autoscaling. Enable control plane logging. Use aws-load-balancer-controller for ALB/NLB integration. Upgrade control plane and nodes regularly.',
    tags: ['aws', 'eks', 'kubernetes', 'containers', 'managed'],
  },
  {
    id: 'AWS-009',
    title: 'AWS Lambda Best Practices',
    domain: 'aws',
    content: 'Lambda runs code without provisioning servers. Max execution time: 15 minutes. Memory: 128MB-10GB (CPU scales with memory). Cold starts: minimize package size, use provisioned concurrency for latency-sensitive functions. Use Lambda layers for shared code. Connect to RDS via RDS Proxy (not direct connections). Use environment variables for configuration.',
    fix: 'Reduce cold start: use smaller deployment packages, avoid unnecessary imports, use provisioned concurrency for critical functions, prefer ARM (Graviton2) runtime for better price-performance.',
    bestPractice: 'Keep functions focused (single responsibility). Use Lambda Powertools for structured logging, tracing, and metrics. Set appropriate memory (test with AWS Lambda Power Tuning). Use reserved concurrency to prevent runaway scaling. Use SQS/SNS for async invocation.',
    tags: ['aws', 'lambda', 'serverless', 'functions', 'cold-start'],
  },
  {
    id: 'AWS-010',
    title: 'AWS CloudFront CDN',
    domain: 'aws',
    content: 'CloudFront is AWS CDN with 400+ edge locations. Features: SSL/TLS, custom domains, origin failover, Lambda@Edge (customize at edge), CloudFront Functions (lightweight edge compute), OAC (Origin Access Control for S3). Use for static assets, API acceleration, and DDoS protection (integrated with Shield).',
    bestPractice: 'Use OAC (not OAI) for S3 origins. Set appropriate cache TTLs (Cache-Control headers). Use cache policies and origin request policies. Enable compression (gzip/brotli). Use CloudFront Functions for simple header manipulation. Use Lambda@Edge for complex logic. Enable access logging.',
    tags: ['aws', 'cloudfront', 'cdn', 'caching', 'performance'],
  },
  {
    id: 'AWS-011',
    title: 'AWS CloudFormation Best Practices',
    domain: 'aws',
    content: 'CloudFormation provisions AWS resources via JSON/YAML templates. Use nested stacks for modular design. Use cross-stack references (Exports) for shared resources. Enable termination protection on production stacks. Use ChangeSets to preview changes before applying. Use CloudFormation drift detection to find manual changes.',
    bestPractice: 'Use YAML (more readable than JSON). Parameterize templates for reuse. Use Conditions for environment-specific resources. Enable stack termination protection. Use deletion policies (Retain/Snapshot) for databases. Consider CDK for complex infrastructure (generates CloudFormation).',
    tags: ['aws', 'cloudformation', 'iac', 'infrastructure', 'automation'],
  },
  {
    id: 'AWS-012',
    title: 'AWS CDK (Cloud Development Kit)',
    domain: 'aws',
    content: 'CDK defines AWS infrastructure using programming languages (TypeScript, Python, Java, Go, .NET). Synthesizes to CloudFormation. Higher-level constructs (L2/L3) provide sensible defaults. L1 constructs map 1:1 to CloudFormation resources. cdk synth generates template, cdk diff shows changes, cdk deploy applies.',
    bestPractice: 'Use L2 constructs when available (they include best-practice defaults). Use cdk diff before deploy. Write unit tests for infrastructure (CDK assertions). Use cdk.context.json for caching context lookups. Organize stacks by lifecycle (network stack, app stack, data stack).',
    tags: ['aws', 'cdk', 'iac', 'infrastructure', 'typescript'],
  },
  {
    id: 'AWS-013',
    title: 'AWS Auto Scaling',
    domain: 'aws',
    content: 'Auto Scaling adjusts EC2 instance count based on demand. Components: Launch Template (instance config), Auto Scaling Group (min/max/desired count), Scaling Policies. Policy types: Target Tracking (maintain metric at target, e.g., CPU at 60%), Step Scaling (different actions at different thresholds), Scheduled (time-based). Predictive Scaling uses ML for anticipated demand.',
    bestPractice: 'Use Target Tracking as default policy. Set min=2 for high availability. Use mixed instance types and purchase options (On-Demand + Spot). Enable instance warmup period. Use lifecycle hooks for pre-launch setup. Set appropriate health check grace period.',
    tags: ['aws', 'auto-scaling', 'ec2', 'scaling', 'elasticity'],
  },
  {
    id: 'AWS-014',
    title: 'AWS ALB vs NLB',
    domain: 'aws',
    content: 'ALB (Application Load Balancer): Layer 7, HTTP/HTTPS, path-based routing, host-based routing, WebSocket support, WAF integration. NLB (Network Load Balancer): Layer 4, TCP/UDP/TLS, ultra-low latency, static IP, preserves source IP, millions of requests per second. Use ALB for web applications, NLB for TCP services, gRPC, or when you need static IPs.',
    bestPractice: 'Use ALB for HTTP/HTTPS workloads (most common). Use NLB for TCP services, gRPC, or extreme performance needs. Enable access logs for both. Use target group health checks. Enable cross-zone load balancing. Use AWS WAF with ALB for web application protection.',
    tags: ['aws', 'alb', 'nlb', 'load-balancer', 'networking'],
  },
  {
    id: 'AWS-015',
    title: 'AWS Route 53',
    domain: 'aws',
    content: 'Route 53 is AWS DNS service. Record types: A (IPv4), AAAA (IPv6), CNAME (alias), MX (mail), TXT (verification/SPF/DKIM), SRV, NS. Routing policies: Simple, Weighted (A/B testing), Latency-based (nearest region), Failover (active-passive), Geolocation, Multi-value answer. Health checks for automatic failover.',
    bestPractice: 'Use Alias records for AWS resources (free, no TTL limitation). Set up health checks for failover. Use low TTL (60s) for services that might need quick failover. Register domains in Route 53 for DNSSEC support. Use private hosted zones for internal DNS.',
    tags: ['aws', 'route53', 'dns', 'networking', 'failover'],
  },
  {
    id: 'AWS-016',
    title: 'AWS CloudWatch Alarms',
    domain: 'aws',
    content: 'CloudWatch monitors AWS resources and applications. Metrics: CPU, memory (requires agent), disk, network, custom metrics. Alarms trigger actions when metrics cross thresholds. Alarm states: OK, ALARM, INSUFFICIENT_DATA. Actions: SNS notification, Auto Scaling, EC2 actions. Use composite alarms to combine multiple alarms.',
    bestPractice: 'Set up alarms for: CPU > 80%, disk > 85%, memory > 90%, ALB 5xx > 1%, RDS connections > 80% max. Use anomaly detection for dynamic thresholds. Install CloudWatch Agent for memory and disk metrics. Use metric math for computed metrics. Set evaluation periods to avoid false alarms.',
    tags: ['aws', 'cloudwatch', 'monitoring', 'alarms', 'metrics'],
  },
  {
    id: 'AWS-017',
    title: 'AWS SNS and SQS',
    domain: 'aws',
    content: 'SNS (Simple Notification Service): Pub/sub messaging, fan-out to multiple subscribers (SQS, Lambda, HTTP, email, SMS). SQS (Simple Queue Service): Message queue, decouples producers and consumers. Standard (at-least-once, best-effort ordering) vs FIFO (exactly-once, ordered). Dead Letter Queue (DLQ) for failed messages.',
    bestPractice: 'Use SNS+SQS fan-out pattern for reliable multi-consumer processing. Always configure DLQ for SQS queues. Set visibility timeout > processing time. Use long polling (WaitTimeSeconds=20) to reduce empty receives. Use FIFO queues only when ordering matters (lower throughput). Enable encryption (SSE-SQS or SSE-KMS).',
    tags: ['aws', 'sns', 'sqs', 'messaging', 'queue', 'pubsub'],
  },
  {
    id: 'AWS-018',
    title: 'AWS DynamoDB',
    domain: 'aws',
    content: 'DynamoDB is a fully managed NoSQL key-value and document database. Single-digit millisecond performance at any scale. Capacity modes: On-Demand (pay per request, good for unpredictable workloads) and Provisioned (cheaper for steady workloads, with auto-scaling). Global tables for multi-region. DAX for microsecond read caching.',
    bestPractice: 'Design access patterns first, then model tables (single-table design). Use composite sort keys for flexible queries. Enable point-in-time recovery. Use on-demand for new tables, switch to provisioned after patterns stabilize. Use DynamoDB Streams for change data capture. Avoid hot partitions (distribute writes evenly).',
    tags: ['aws', 'dynamodb', 'nosql', 'database', 'serverless'],
  },
  {
    id: 'AWS-019',
    title: 'AWS Cost Optimization: Reserved Instances and Savings Plans',
    domain: 'aws',
    content: 'Reserved Instances (RI): 1 or 3 year commitment for specific instance type, up to 72% discount. Savings Plans: Flexible commitment to $/hour of compute, covers EC2, Fargate, Lambda. Compute Savings Plans (most flexible), EC2 Instance Savings Plans (most discount). Spot Instances: up to 90% discount, can be interrupted with 2-min warning.',
    fix: 'Analyze usage with Cost Explorer RI/SP recommendations. Start with Compute Savings Plans for flexibility. Use Spot for fault-tolerant workloads (batch processing, CI/CD, stateless web servers with auto-scaling).',
    bestPractice: 'Cover steady-state with Savings Plans (60-70% of usage). Use Spot for variable workloads. Use On-Demand for the rest. Review and adjust commitments quarterly. Use AWS Compute Optimizer for right-sizing recommendations.',
    tags: ['aws', 'cost', 'reserved-instances', 'savings-plans', 'spot', 'optimization'],
  },
  {
    id: 'AWS-020',
    title: 'AWS Well-Architected Framework',
    domain: 'aws',
    content: 'Six pillars: 1) Operational Excellence — automate, anticipate failure, learn from events. 2) Security — least privilege, traceability, encryption. 3) Reliability — automatic recovery, horizontal scaling, testing recovery. 4) Performance Efficiency — right-size, experiment, serverless. 5) Cost Optimization — eliminate waste, right-size, use pricing models. 6) Sustainability — maximize utilization, reduce downstream resources.',
    bestPractice: 'Run Well-Architected Review annually using AWS Well-Architected Tool. Address high-risk items first. Use the review as a learning tool, not a compliance checkbox. Each pillar has specific best practices and questions to evaluate your architecture.',
    tags: ['aws', 'well-architected', 'architecture', 'best-practices', 'framework'],
  },
  {
    id: 'AWS-021',
    title: 'AWS ECR (Elastic Container Registry)',
    domain: 'aws',
    content: 'ECR is a managed Docker container registry. Features: image scanning (on push or on-demand), lifecycle policies (auto-delete old images), cross-region replication, immutable tags, encryption at rest. Use ECR for ECS/EKS deployments. Pull-through cache for public registries (Docker Hub, GitHub).',
    bestPractice: 'Enable scan on push for vulnerability detection. Set lifecycle policies to delete untagged images after 7 days and keep only last 10 tagged images. Use immutable tags for production. Use ECR pull-through cache to avoid Docker Hub rate limits.',
    tags: ['aws', 'ecr', 'docker', 'registry', 'containers'],
  },
  {
    id: 'AWS-022',
    title: 'AWS Secrets Manager',
    domain: 'aws',
    content: 'Secrets Manager stores and rotates secrets (database credentials, API keys, tokens). Automatic rotation with Lambda functions. Integration with RDS for automatic password rotation. Pricing: $0.40/secret/month + $0.05/10,000 API calls. Alternative: SSM Parameter Store SecureString (free for standard, limited features).',
    bestPractice: 'Use Secrets Manager for database credentials with automatic rotation. Use SSM Parameter Store for configuration (cheaper). Enable automatic rotation every 30-90 days. Use resource policies for cross-account access. Cache secrets in application (TTL 5 minutes) to reduce API calls.',
    tags: ['aws', 'secrets', 'security', 'credentials', 'rotation'],
  },
  {
    id: 'AWS-023',
    title: 'AWS WAF (Web Application Firewall)',
    domain: 'aws',
    content: 'WAF protects web applications from common exploits. Deploy on ALB, CloudFront, API Gateway, AppSync. Use AWS Managed Rules for common threats (SQL injection, XSS, known bad IPs). Create custom rules for rate limiting, geo-blocking, or application-specific protection. Web ACL evaluates rules in priority order.',
    bestPractice: 'Enable AWS Managed Rules: AWSManagedRulesCommonRuleSet, AWSManagedRulesSQLiRuleSet, AWSManagedRulesKnownBadInputsRuleSet. Add rate-based rules (e.g., 2000 requests/5 min per IP). Start in Count mode before switching to Block. Use WAF logging to S3 for analysis.',
    tags: ['aws', 'waf', 'security', 'firewall', 'web-protection'],
  },
  {
    id: 'AWS-024',
    title: 'AWS Systems Manager (SSM)',
    domain: 'aws',
    content: 'SSM provides operational management for AWS resources. Key features: Session Manager (SSH-less shell access), Run Command (execute commands across instances), Parameter Store (config/secrets), Patch Manager (automated patching), State Manager (desired state), Automation (runbooks). Requires SSM Agent on instances.',
    bestPractice: 'Use Session Manager instead of SSH (no open port 22, full audit trail). Use Parameter Store for configuration. Use Patch Manager for automated OS patching. Use Automation for common operational tasks (restart instances, create AMIs). Enable SSM Agent auto-update.',
    tags: ['aws', 'ssm', 'systems-manager', 'operations', 'management'],
  },
  {
    id: 'AWS-025',
    title: 'AWS Transit Gateway',
    domain: 'aws',
    content: 'Transit Gateway connects VPCs and on-premises networks through a central hub. Replaces complex VPC peering mesh. Supports transitive routing, route tables for network segmentation, multicast, inter-region peering. Simplifies network architecture when you have 3+ VPCs.',
    bestPractice: 'Use Transit Gateway when you have 3+ VPCs. Create separate route tables for shared services, production, and development. Enable flow logs for security monitoring. Use Transit Gateway Network Manager for visualization. Consider cost: $0.05/GB data processed.',
    tags: ['aws', 'transit-gateway', 'networking', 'vpc', 'connectivity'],
  },
  {
    id: 'AWS-026',
    title: 'AWS ElastiCache (Redis/Memcached)',
    domain: 'aws',
    content: 'ElastiCache provides managed Redis or Memcached. Redis: rich data structures, persistence, replication, pub/sub, Lua scripting. Memcached: simple key-value, multi-threaded, no persistence. Use Redis for: session store, caching, queues, leaderboards. Use cluster mode for horizontal scaling (up to 500 nodes).',
    bestPractice: 'Use Redis for most use cases (more features than Memcached). Enable Multi-AZ with automatic failover. Set appropriate eviction policy (allkeys-lru for caching). Monitor memory usage, evictions, and cache hit rate. Use reserved nodes for steady workloads (up to 55% savings).',
    tags: ['aws', 'elasticache', 'redis', 'memcached', 'caching'],
  },
  {
    id: 'AWS-027',
    title: 'AWS EBS Volume Types',
    domain: 'aws',
    content: 'EBS volume types: gp3 (general purpose SSD, 3000 IOPS baseline, cheapest SSD), gp2 (previous gen, burst IOPS based on size), io2 Block Express (high performance, up to 256,000 IOPS), st1 (throughput-optimized HDD, sequential workloads), sc1 (cold HDD, infrequent access). gp3 is the default choice for most workloads.',
    bestPractice: 'Use gp3 for most workloads (cheaper than gp2, configurable IOPS/throughput). Use io2 for databases needing consistent high IOPS. Enable EBS encryption by default (account-level setting). Take regular snapshots. Use EBS-optimized instances. Monitor with CloudWatch BurstBalance metric.',
    tags: ['aws', 'ebs', 'storage', 'volumes', 'iops'],
  },
  {
    id: 'AWS-028',
    title: 'AWS S3 Lifecycle Policies',
    domain: 'aws',
    content: 'S3 lifecycle policies automatically transition objects between storage classes or expire them. Storage classes: Standard, Intelligent-Tiering, Standard-IA (infrequent access), One Zone-IA, Glacier Instant Retrieval, Glacier Flexible Retrieval, Glacier Deep Archive. Transition rules reduce costs for aging data.',
    bestPractice: 'Typical policy: Standard for 30 days, transition to Standard-IA after 30 days, Glacier after 90 days, Deep Archive after 365 days, expire after 7 years. Use Intelligent-Tiering for unpredictable access patterns. Set up lifecycle rules for incomplete multipart uploads (delete after 7 days). Enable S3 Storage Lens for analytics.',
    tags: ['aws', 's3', 'lifecycle', 'storage', 'cost-optimization'],
  },
  {
    id: 'AWS-029',
    title: 'AWS CloudTrail',
    domain: 'aws',
    content: 'CloudTrail logs all API calls in your AWS account. Essential for security auditing, compliance, and troubleshooting. Trail types: management events (default, free for one trail), data events (S3/Lambda/DynamoDB operations, additional cost), insight events (detect unusual activity). Logs delivered to S3 bucket.',
    bestPractice: 'Enable CloudTrail in all regions with a single organization trail. Enable log file integrity validation. Send logs to a centralized S3 bucket in a security account. Set up CloudWatch Logs integration for real-time alerting. Enable CloudTrail Insights for anomaly detection. Retain logs for at least 1 year.',
    tags: ['aws', 'cloudtrail', 'security', 'audit', 'logging', 'compliance'],
  },
  {
    id: 'AWS-030',
    title: 'AWS Config',
    domain: 'aws',
    content: 'AWS Config tracks resource configuration changes and evaluates compliance. Config Rules check if resources comply with desired configurations (e.g., S3 buckets must be encrypted, Security Groups must not allow 0.0.0.0/0 on port 22). Conformance Packs bundle related rules. Remediation actions can auto-fix non-compliant resources.',
    bestPractice: 'Enable AWS Config in all regions. Use managed rules for common checks: s3-bucket-public-read-prohibited, restricted-ssh, rds-storage-encrypted, encrypted-volumes. Set up auto-remediation for critical rules. Use conformance packs for compliance frameworks (CIS, PCI DSS).',
    tags: ['aws', 'config', 'compliance', 'governance', 'security'],
  },
  {
    id: 'AWS-031',
    title: 'AWS Organizations and SCPs',
    domain: 'aws',
    content: 'AWS Organizations manages multiple AWS accounts centrally. Service Control Policies (SCPs) set permission guardrails across accounts. Use separate accounts for: production, staging, development, security/audit, shared services, sandbox. Consolidated billing for volume discounts.',
    bestPractice: 'Use a multi-account strategy (minimum: production, staging, security, shared). Apply SCPs to prevent: disabling CloudTrail, leaving certain regions, deleting critical resources. Use AWS Control Tower for automated account provisioning and guardrails. Never run workloads in the management account.',
    tags: ['aws', 'organizations', 'scp', 'multi-account', 'governance'],
  },
  {
    id: 'AWS-032',
    title: 'AWS KMS (Key Management Service)',
    domain: 'aws',
    content: 'KMS creates and manages encryption keys. Customer Managed Keys (CMK) for full control over rotation and policies. AWS Managed Keys for simpler management. Integrates with most AWS services (S3, EBS, RDS, Secrets Manager). Key policies control access. Automatic key rotation every year for symmetric keys.',
    bestPractice: 'Use customer-managed keys for sensitive data. Enable automatic key rotation. Use key policies (not just IAM) for access control. Use different keys for different data classifications. Monitor key usage with CloudTrail. Use grants for temporary cross-service access.',
    tags: ['aws', 'kms', 'encryption', 'security', 'keys'],
  },
  {
    id: 'AWS-033',
    title: 'AWS Elastic Beanstalk',
    domain: 'aws',
    content: 'Elastic Beanstalk is a PaaS for deploying web applications. Supports Node.js, Python, Java, .NET, PHP, Ruby, Go, Docker. Manages EC2, ALB, Auto Scaling, RDS automatically. Use .ebextensions for customization. Environment types: Web Server (HTTP), Worker (SQS processing).',
    bestPractice: 'Use for quick deployments when full control is not needed. Decouple RDS from Beanstalk environment (create RDS separately). Use immutable deployment policy for safer updates. Set up Blue/Green with environment swap. Use .platform hooks for advanced customization. Consider migration to ECS/EKS for complex applications.',
    tags: ['aws', 'elastic-beanstalk', 'paas', 'deployment', 'managed'],
  },
  {
    id: 'AWS-034',
    title: 'AWS Step Functions',
    domain: 'aws',
    content: 'Step Functions orchestrates serverless workflows as state machines. Visual workflow designer. States: Task, Choice, Parallel, Wait, Map, Pass, Succeed, Fail. Express workflows for high-volume short-duration (up to 5 min). Standard workflows for long-running (up to 1 year). Integrates with Lambda, ECS, SNS, SQS, DynamoDB, and 200+ AWS services.',
    bestPractice: 'Use Standard workflows for orchestration, Express for data processing. Implement error handling with Retry and Catch. Use Map state for parallel processing. Keep Lambda functions focused (single task). Use Step Functions for anything requiring coordination between multiple services.',
    tags: ['aws', 'step-functions', 'serverless', 'orchestration', 'workflow'],
  },
  {
    id: 'AWS-035',
    title: 'AWS GuardDuty',
    domain: 'aws',
    content: 'GuardDuty is a threat detection service analyzing CloudTrail, VPC Flow Logs, DNS logs, and S3 data events. Detects: compromised instances (cryptocurrency mining, C&C communication), compromised credentials (anomalous API calls, unusual regions), reconnaissance (port scanning, failed logins). Machine learning-based, no agents needed.',
    bestPractice: 'Enable GuardDuty in all regions and all accounts via Organizations. Set up SNS notifications for high-severity findings. Integrate with Security Hub for centralized view. Auto-remediate common findings with Lambda (e.g., quarantine compromised instances). Review and tune suppression rules for false positives.',
    tags: ['aws', 'guardduty', 'security', 'threat-detection', 'monitoring'],
  },
  {
    id: 'AWS-036',
    title: 'AWS EFS (Elastic File System)',
    domain: 'aws',
    content: 'EFS is a managed NFS file system. Shared storage across multiple EC2 instances and containers. Storage classes: Standard and Infrequent Access (IA). Throughput modes: Bursting (scales with size), Provisioned (fixed), Elastic (auto-scales). Use for shared application data, CMS content, home directories, CI/CD artifacts.',
    bestPractice: 'Use lifecycle management to move files to IA after 30 days. Use Elastic throughput for unpredictable workloads. Enable encryption at rest and in transit. Set up mount targets in each AZ. Use EFS access points for application-specific root directories. Monitor with CloudWatch BurstCreditBalance.',
    tags: ['aws', 'efs', 'storage', 'nfs', 'shared-filesystem'],
  },
  {
    id: 'AWS-037',
    title: 'AWS EventBridge',
    domain: 'aws',
    content: 'EventBridge is a serverless event bus. Routes events from AWS services, SaaS applications, and custom applications. Rules match events and route to targets (Lambda, SQS, SNS, Step Functions). Use for event-driven architectures, decoupling services. Schema registry for event discovery. Archive and replay events.',
    bestPractice: 'Use EventBridge over CloudWatch Events (superset). Create custom event buses for application events. Use schema discovery for documentation. Archive events for replay and debugging. Use input transformers to reshape events before delivery. Implement dead-letter queues for failed deliveries.',
    tags: ['aws', 'eventbridge', 'events', 'serverless', 'event-driven'],
  },
  {
    id: 'AWS-038',
    title: 'AWS Cognito',
    domain: 'aws',
    content: 'Cognito provides authentication, authorization, and user management. User Pools: user directory with sign-up/sign-in, MFA, social login (Google, Facebook, Apple). Identity Pools: temporary AWS credentials for accessing AWS services. Use for web/mobile app authentication. Supports OIDC and SAML federation.',
    bestPractice: 'Use User Pools for application authentication. Enable MFA. Customize email templates. Use Lambda triggers for custom workflows (pre-sign-up validation, post-confirmation). Use hosted UI for quick setup. Set appropriate token expiration. Use groups for authorization.',
    tags: ['aws', 'cognito', 'authentication', 'identity', 'user-management'],
  },
  {
    id: 'AWS-039',
    title: 'AWS Cost Explorer and Budgets',
    domain: 'aws',
    content: 'Cost Explorer visualizes AWS spending patterns. Filter by service, account, tag, region. Shows usage-based and cost-based views. Forecasts future costs. Right-sizing recommendations for EC2. AWS Budgets sets alerts when costs or usage exceed thresholds. Supports cost, usage, RI utilization, and SP coverage budgets.',
    bestPractice: 'Set up monthly cost budgets with 80% and 100% threshold alerts. Use tags (Project, Environment, Team) for cost allocation. Review Cost Explorer weekly. Enable cost anomaly detection. Use right-sizing recommendations. Set up budget actions to auto-stop resources when budget exceeded.',
    tags: ['aws', 'cost', 'billing', 'budgets', 'finops'],
  },
  {
    id: 'AWS-040',
    title: 'AWS PrivateLink and VPC Endpoints',
    domain: 'aws',
    content: 'VPC Endpoints enable private connectivity to AWS services without internet. Interface endpoints (PrivateLink): ENI with private IP, supports most services. Gateway endpoints: route table entry, supports S3 and DynamoDB only (free). PrivateLink eliminates need for NAT Gateway, internet gateway, or VPN for AWS service access.',
    bestPractice: 'Use Gateway endpoints for S3 and DynamoDB (free, simple). Use Interface endpoints for ECR, CloudWatch, Secrets Manager, KMS. This reduces NAT Gateway costs and improves security. Use VPC endpoint policies to restrict access. Enable private DNS for seamless integration.',
    tags: ['aws', 'privatelink', 'vpc-endpoints', 'networking', 'security'],
  },
  {
    id: 'AWS-041',
    title: 'AWS Backup',
    domain: 'aws',
    content: 'AWS Backup centralizes backup management across AWS services: EBS, RDS, DynamoDB, EFS, FSx, EC2, S3. Create backup plans with schedules and retention. Cross-region and cross-account backups for disaster recovery. Vault lock for immutable backups (compliance). Audit Manager for backup compliance reporting.',
    bestPractice: 'Create backup plans by tier: critical (hourly, 30-day retention, cross-region), standard (daily, 14-day retention), archive (weekly, 1-year retention). Enable vault lock for compliance workloads. Test restore procedures quarterly. Use tags to assign resources to backup plans.',
    tags: ['aws', 'backup', 'disaster-recovery', 'data-protection', 'compliance'],
  },
  {
    id: 'AWS-042',
    title: 'AWS Global Accelerator',
    domain: 'aws',
    content: 'Global Accelerator improves application availability and performance using AWS global network. Provides static anycast IP addresses. Routes traffic to optimal endpoint (ALB, NLB, EC2, Elastic IP) based on health, geography, and routing policies. Faster than public internet (uses AWS backbone). DDoS protection via Shield integration.',
    bestPractice: 'Use for multi-region applications needing deterministic routing. Combine with health checks for automatic failover between regions. Use traffic dials for weighted routing (canary between regions). Consider vs CloudFront: GA is for non-HTTP protocols and when you need static IPs.',
    tags: ['aws', 'global-accelerator', 'networking', 'performance', 'multi-region'],
  },
];
