'use strict';

module.exports = [
  {
    id: 'GCP-001',
    title: 'GKE (Google Kubernetes Engine)',
    domain: 'gcp',
    content: 'GKE is managed Kubernetes on Google Cloud. Two modes: Standard (you manage node pools) and Autopilot (Google manages nodes, pay per pod). Features: auto-scaling, auto-repair, auto-upgrade, Workload Identity (IAM for pods), GKE Sandbox (gVisor), Binary Authorization. Integrates with Cloud Monitoring and Cloud Logging.',
    bestPractice: 'Use Autopilot for most workloads (simpler, cost-efficient). Use Workload Identity instead of service account keys. Enable shielded GKE nodes. Use node auto-provisioning with Autopilot. Set up GKE Gateway API for ingress. Enable Binary Authorization for supply chain security.',
    tags: ['gcp', 'gke', 'kubernetes', 'containers', 'managed'],
  },
  {
    id: 'GCP-002',
    title: 'Cloud Run',
    domain: 'gcp',
    content: 'Cloud Run runs containers serverlessly. Scales from zero to thousands of instances. Pay only for request processing time. Supports any language/framework via containers. Features: automatic HTTPS, custom domains, traffic splitting (canary), min/max instances, CPU allocation (always-on or request-only). Max request timeout: 60 minutes.',
    bestPractice: 'Use for stateless HTTP services. Set min-instances=1 for latency-sensitive services (avoid cold starts). Use concurrency setting to match your app (default 80). Use Cloud Run Jobs for batch workloads. Use traffic splitting for gradual rollouts. Connect to Cloud SQL via Unix socket connector.',
    tags: ['gcp', 'cloud-run', 'serverless', 'containers', 'autoscaling'],
  },
  {
    id: 'GCP-003',
    title: 'Cloud SQL',
    domain: 'gcp',
    content: 'Cloud SQL is managed PostgreSQL, MySQL, and SQL Server. Features: automated backups, high availability (regional), read replicas, point-in-time recovery, automatic storage increase, maintenance windows, Cloud SQL Proxy for secure connections, IAM authentication.',
    bestPractice: 'Use Cloud SQL Proxy or Auth Proxy for connections (handles SSL and IAM). Enable high availability for production. Use automated backups with 7+ day retention. Enable query insights for performance monitoring. Use private IP and VPC peering. Set maintenance windows during low-traffic periods.',
    tags: ['gcp', 'cloud-sql', 'database', 'postgresql', 'mysql', 'managed'],
  },
  {
    id: 'GCP-004',
    title: 'BigQuery',
    domain: 'gcp',
    content: 'BigQuery is a serverless data warehouse for analytics. Processes petabytes in seconds using columnar storage. Pricing: on-demand ($5/TB scanned) or flat-rate (slots). Features: standard SQL, federated queries (Cloud Storage, Sheets), materialized views, BI Engine (in-memory analysis), ML (BigQuery ML). Streaming inserts for real-time data.',
    bestPractice: 'Partition tables by date to reduce scanned data. Use clustered tables for frequently filtered columns. Use SELECT only needed columns (never SELECT *). Use preview before running expensive queries. Set up cost controls with custom quotas. Use BigQuery Reservations for predictable costs at scale.',
    tags: ['gcp', 'bigquery', 'analytics', 'data-warehouse', 'sql'],
  },
  {
    id: 'GCP-005',
    title: 'GCP IAM Best Practices',
    domain: 'gcp',
    content: 'GCP IAM uses roles (predefined and custom) bound to members (users, groups, service accounts). Hierarchy: Organization > Folder > Project > Resource. Permissions inherit downward. Use predefined roles over basic roles (Owner/Editor/Viewer are too broad). Service accounts for applications.',
    bestPractice: 'Never use Owner/Editor roles. Use predefined roles with least privilege. Use Workload Identity Federation instead of service account keys. Enable IAM Recommender for unused permission detection. Use IAM Conditions for context-aware access. Organize with folders and use IAM at folder level for consistent policy.',
    tags: ['gcp', 'iam', 'security', 'access-control', 'permissions'],
  },
  {
    id: 'GCP-006',
    title: 'Terraform with GCP',
    domain: 'gcp',
    content: 'Terraform manages GCP infrastructure with the google and google-beta providers. Use remote state in GCS bucket with state locking. Google provides Terraform modules: terraform-google-modules on GitHub. Use Cloud Foundation Toolkit for enterprise-grade modules. Workload Identity Federation for Terraform Cloud/GitHub Actions authentication.',
    bestPractice: 'Use GCS backend with versioning and locking enabled. Use google-beta provider for new features. Pin provider versions. Use modules for reusable components (VPC, GKE, Cloud SQL). Implement CI/CD with terraform plan in PR, terraform apply on merge. Use Workload Identity Federation (no service account keys).',
    tags: ['gcp', 'terraform', 'iac', 'infrastructure', 'automation'],
  },
  {
    id: 'GCP-007',
    title: 'Compute Engine',
    domain: 'gcp',
    content: 'Compute Engine provides VMs on Google Cloud. Machine families: General-purpose (E2, N2, N2D, T2D), Compute-optimized (C2, C2D, H3), Memory-optimized (M1, M2, M3), Accelerator-optimized (A2, G2). Preemptible VMs (up to 91% discount, max 24h) and Spot VMs (no max duration, variable pricing). Custom machine types for exact CPU/memory ratios.',
    bestPractice: 'Use E2 instances for cost-effective general workloads. Use custom machine types to avoid over-provisioning. Use Spot VMs for fault-tolerant batch workloads. Use managed instance groups (MIG) for auto-scaling and auto-healing. Enable Ops Agent for monitoring. Use OS Login instead of SSH keys.',
    tags: ['gcp', 'compute-engine', 'vm', 'instances', 'compute'],
  },
  {
    id: 'GCP-008',
    title: 'Cloud Storage',
    domain: 'gcp',
    content: 'Cloud Storage is object storage with four classes: Standard (frequent access), Nearline (monthly access), Coldline (quarterly access), Archive (yearly access). Features: Object Versioning, Object Lifecycle Management, uniform bucket-level access, signed URLs, Cloud CDN integration, strong consistency.',
    bestPractice: 'Use uniform bucket-level access (disable ACLs). Enable Object Versioning for data protection. Set lifecycle rules to transition or delete objects. Use Autoclass for automatic storage class management. Enable public access prevention at org level. Use signed URLs/cookies for temporary access.',
    tags: ['gcp', 'cloud-storage', 'gcs', 'object-storage', 'buckets'],
  },
  {
    id: 'GCP-009',
    title: 'Cloud Functions',
    domain: 'gcp',
    content: 'Cloud Functions is GCP serverless FaaS. 2nd gen (recommended) runs on Cloud Run infrastructure with longer timeouts (60min), larger instances (16GB/8vCPU), concurrency (up to 1000), and CloudEvents support. Triggers: HTTP, Pub/Sub, Cloud Storage events, Firestore, Firebase. Runtime: Node.js, Python, Go, Java, Ruby, PHP, .NET.',
    bestPractice: 'Use 2nd gen for all new functions. Use minimum instances for latency-sensitive functions. Set appropriate memory (CPU scales proportionally). Use Pub/Sub triggers for async processing. Keep functions focused. Use Secret Manager for credentials. Enable VPC connector for private resource access.',
    tags: ['gcp', 'cloud-functions', 'serverless', 'faas', 'event-driven'],
  },
  {
    id: 'GCP-010',
    title: 'Pub/Sub',
    domain: 'gcp',
    content: 'Pub/Sub is a real-time messaging service. Publishers send messages to topics, subscribers receive from subscriptions. Delivery types: pull (subscriber requests messages) and push (Pub/Sub sends to endpoint). Features: ordering, filtering, dead-letter topics, exactly-once delivery, schema validation. Global scale with 500M+ messages/sec.',
    bestPractice: 'Use pull subscriptions for most cases. Set appropriate acknowledgment deadline (longer than processing time). Use dead-letter topics for failed messages. Enable message ordering only when needed (reduces throughput). Use BigQuery subscriptions for analytics. Set message retention to 7 days for replay capability.',
    tags: ['gcp', 'pubsub', 'messaging', 'event-driven', 'queue'],
  },
  {
    id: 'GCP-011',
    title: 'Cloud CDN',
    domain: 'gcp',
    content: 'Cloud CDN caches content at Google edge points of presence. Integrates with external HTTP(S) load balancer. Cache modes: USE_ORIGIN_HEADERS (respect Cache-Control), CACHE_ALL_STATIC (auto-detect static content), FORCE_CACHE_ALL (cache everything with configurable TTL). Supports cache invalidation, signed URLs, and signed cookies.',
    bestPractice: 'Use CACHE_ALL_STATIC for typical web applications. Set appropriate cache TTLs in origin Cache-Control headers. Use signed URLs for premium content. Enable negative caching (cache 404s briefly). Monitor cache hit ratio in Cloud Monitoring (aim for >90% for static content). Use Cloud CDN with Cloud Storage for static websites.',
    tags: ['gcp', 'cdn', 'caching', 'performance', 'edge'],
  },
  {
    id: 'GCP-012',
    title: 'VPC and Firewall Rules',
    domain: 'gcp',
    content: 'GCP VPC is global (spans all regions). Subnets are regional. Firewall rules are at VPC level, matched by network tags or service accounts. Default rules: allow egress, deny ingress (except inter-VM same network). Priority-based evaluation (0-65535, lower = higher priority). Use hierarchical firewall policies in organizations.',
    bestPractice: 'Use service account-based firewall rules over network tags (more secure). Create allow rules for specific traffic, keep default deny. Use Private Google Access for internal-only service access. Enable Flow Logs for security analysis. Use Shared VPC for multi-project networking. Use VPC Service Controls for data exfiltration protection.',
    tags: ['gcp', 'vpc', 'firewall', 'networking', 'security'],
  },
  {
    id: 'GCP-013',
    title: 'Cloud Build',
    domain: 'gcp',
    content: 'Cloud Build is GCP CI/CD platform. Builds run in Docker containers. Define steps in cloudbuild.yaml. Integrates with GitHub, GitLab, Bitbucket. Triggers: push, PR, tag, manual, Pub/Sub. Built-in builders for Docker, gcloud, kubectl, terraform. 120 free build-minutes/day. Private worker pools for VPC access.',
    bestPractice: 'Use kaniko builder for Docker builds (no Docker daemon, better caching). Use private pools for builds needing VPC access. Cache dependencies in Cloud Storage. Use substitutions for parameterized builds. Set appropriate timeouts. Use Cloud Build triggers with branch filters. Combine with Binary Authorization for supply chain security.',
    tags: ['gcp', 'cloud-build', 'ci-cd', 'automation', 'build'],
  },
  {
    id: 'GCP-014',
    title: 'Artifact Registry',
    domain: 'gcp',
    content: 'Artifact Registry stores Docker images, npm packages, Maven artifacts, Python packages, and more. Replaces Container Registry. Features: vulnerability scanning, IAM access control, regional and multi-regional repos, cleanup policies, remote repositories (proxy for Docker Hub, npm).',
    bestPractice: 'Use Artifact Registry over Container Registry (more features, unified). Enable vulnerability scanning on push. Set cleanup policies to delete old untagged images. Use remote repositories to cache upstream packages (Docker Hub, npm). Use Artifact Analysis for SBOM and provenance.',
    tags: ['gcp', 'artifact-registry', 'docker', 'registry', 'packages'],
  },
  {
    id: 'GCP-015',
    title: 'Cloud Monitoring (Stackdriver)',
    domain: 'gcp',
    content: 'Cloud Monitoring collects metrics, creates dashboards, and sets up alerting. Supports GCP services, AWS, and custom metrics. Features: uptime checks, dashboards, alerting policies, service monitoring (SLOs), Managed Prometheus (PromQL queries). Custom metrics via OpenTelemetry or client libraries.',
    bestPractice: 'Set up alerting for key metrics: CPU, memory, disk, error rate, latency. Use service monitoring to define SLOs. Create custom dashboards per team. Use Managed Prometheus for Kubernetes metrics. Enable Ops Agent on VMs for system and application metrics. Use notification channels (email, Slack, PagerDuty, webhook).',
    tags: ['gcp', 'monitoring', 'stackdriver', 'alerting', 'observability'],
  },
  {
    id: 'GCP-016',
    title: 'Cloud Logging',
    domain: 'gcp',
    content: 'Cloud Logging ingests, stores, and analyzes log data. Auto-collects from GCP services. Log Router routes logs to: Cloud Logging buckets, Cloud Storage, BigQuery, Pub/Sub. Log-based metrics for custom monitoring. Log Analytics for SQL-based log analysis. Default retention: 30 days (400 days with upgrades).',
    bestPractice: 'Use structured logging (JSON) for easy querying. Set up log sinks to BigQuery for long-term analysis. Create log-based metrics for error counting. Use exclusion filters to reduce ingestion costs (debug logs in prod). Export audit logs to a separate project for security. Use Log Analytics for ad-hoc investigation.',
    tags: ['gcp', 'logging', 'observability', 'log-router', 'analysis'],
  },
  {
    id: 'GCP-017',
    title: 'Cloud Spanner',
    domain: 'gcp',
    content: 'Cloud Spanner is a globally distributed relational database. Combines strong consistency with horizontal scalability. SQL interface with schema, indexes, and transactions. Scales from single-region to multi-region. Automatic replication and sharding. 99.999% availability SLA for multi-region configurations.',
    bestPractice: 'Use for globally distributed applications needing strong consistency. Design primary keys to distribute writes evenly (avoid hotspots). Use interleaved tables for parent-child relationships. Monitor CPU utilization (keep below 65%). Start small and scale nodes based on demand. Use emulator for development.',
    tags: ['gcp', 'spanner', 'database', 'global', 'distributed', 'relational'],
  },
  {
    id: 'GCP-018',
    title: 'Cloud Armor',
    domain: 'gcp',
    content: 'Cloud Armor provides DDoS protection and WAF capabilities. Integrates with external HTTP(S) load balancer. Features: preconfigured WAF rules (OWASP Top 10), custom rules with CEL expressions, rate limiting, bot management, adaptive protection (ML-based). Edge security policies filter traffic at Google edge.',
    bestPractice: 'Enable preconfigured rules for SQL injection and XSS. Use rate limiting per IP. Enable adaptive protection for DDoS mitigation. Use named IP lists for allow/deny lists. Start in preview mode before enforcing. Use Cloud Armor with Cloud CDN for edge protection.',
    tags: ['gcp', 'cloud-armor', 'security', 'waf', 'ddos', 'firewall'],
  },
  {
    id: 'GCP-019',
    title: 'Secret Manager',
    domain: 'gcp',
    content: 'Secret Manager stores API keys, passwords, certificates, and other sensitive data. Features: versioning, automatic rotation, IAM access control, audit logging, replication policies (automatic or user-managed). Integrates with Cloud Functions, Cloud Run, GKE (via CSI driver or Workload Identity).',
    bestPractice: 'Use Secret Manager instead of environment variables for secrets. Access secrets at runtime, not build time. Use IAM for access control (principle of least privilege). Enable audit logging. Set up automatic rotation for database passwords. Use version aliases for zero-downtime rotation.',
    tags: ['gcp', 'secret-manager', 'security', 'credentials', 'secrets'],
  },
  {
    id: 'GCP-020',
    title: 'GCP Load Balancing',
    domain: 'gcp',
    content: 'GCP offers global and regional load balancers. External HTTP(S) LB: global, L7, integrates with Cloud CDN, Cloud Armor, and Serverless NEGs. External TCP/UDP Network LB: regional, L4, passthrough. Internal HTTP(S) LB: regional, L7, for internal services. Internal TCP/UDP LB: regional, L4, for internal TCP services. Proxy Network LB: global, L4.',
    bestPractice: 'Use external HTTP(S) LB for web applications (global anycast, SSL termination, Cloud CDN). Use Serverless NEGs for Cloud Run/Functions/App Engine backends. Enable Cloud CDN for cacheable content. Use health checks with appropriate intervals. Use URL maps for path-based routing to different backends.',
    tags: ['gcp', 'load-balancer', 'networking', 'traffic', 'global'],
  },
  {
    id: 'GCP-021',
    title: 'GCP Cost Management',
    domain: 'gcp',
    content: 'Cost management tools: Billing reports, Cost Table, Budget alerts, Committed Use Discounts (CUD, 1-3 year for 37-55% savings), Sustained Use Discounts (automatic for VMs running 25%+ of month). Use recommendations for idle resources, oversized instances, and unused IP addresses. Labels for cost allocation.',
    bestPractice: 'Set up budget alerts at 50%, 80%, 100%. Use CUDs for steady-state compute and database. Use Spot VMs for batch workloads. Use labels for cost allocation by team/project/environment. Review active recommendations weekly. Schedule non-production environments to shut down after hours.',
    tags: ['gcp', 'cost', 'billing', 'optimization', 'cud', 'budgets'],
  },
  {
    id: 'GCP-022',
    title: 'Cloud Memorystore',
    domain: 'gcp',
    content: 'Memorystore provides managed Redis and Memcached. Redis: Standard tier (failover) and Basic tier (no failover). Supports Redis 6.x and 7.x. Up to 300GB memory. Memorystore for Redis Cluster for horizontal scaling. Use for caching, session management, leaderboards, and message brokering.',
    bestPractice: 'Use Standard tier (HA) for production Redis. Connect from GKE/Cloud Run via VPC connector or Private Service Connect. Set eviction policy (allkeys-lru for cache). Monitor memory usage and evictions. Use Redis Cluster for datasets > 16GB or high throughput needs.',
    tags: ['gcp', 'memorystore', 'redis', 'memcached', 'caching'],
  },
  {
    id: 'GCP-023',
    title: 'Workload Identity Federation',
    domain: 'gcp',
    content: 'Workload Identity Federation allows external workloads (AWS, Azure, GitHub Actions, GitLab CI, Terraform Cloud) to access GCP resources without service account keys. Uses OIDC or SAML tokens to impersonate a service account. Eliminates key management and rotation concerns. Essential for CI/CD pipelines.',
    bestPractice: 'Always use Workload Identity Federation over service account keys. Set up attribute conditions to restrict access (e.g., only from specific GitHub repos/branches). Use with GitHub Actions for deployments. Combine with IAM conditions for fine-grained access. Audit usage with Cloud Audit Logs.',
    tags: ['gcp', 'workload-identity', 'security', 'federation', 'ci-cd'],
  },
  {
    id: 'GCP-024',
    title: 'Cloud NAT',
    domain: 'gcp',
    content: 'Cloud NAT provides outbound internet access for VMs without external IPs. Regional resource. Supports automatic or manual NAT IP allocation. Port allocation: static (default 64 ports/VM) or dynamic. Logging for connection tracking. Use for private GKE nodes, private Cloud SQL, and VMs that need outbound-only access.',
    bestPractice: 'Use dynamic port allocation to avoid port exhaustion. Enable endpoint-independent mapping for connection-heavy workloads. Set up Cloud NAT logging for troubleshooting. Use manual IP allocation for allowlisting. Monitor NAT gateway metrics (allocated ports, dropped connections).',
    tags: ['gcp', 'cloud-nat', 'networking', 'egress', 'private'],
  },
  {
    id: 'GCP-025',
    title: 'GCP Organization Policies',
    domain: 'gcp',
    content: 'Organization policies enforce constraints across your GCP org. Examples: restrict resource locations (data residency), disable service account key creation, require OS Login, enforce uniform bucket-level access, restrict VM external IPs, disable serial port access. Applied at org, folder, or project level.',
    bestPractice: 'Enable key policies: constraints/iam.disableServiceAccountKeyCreation, constraints/compute.requireOsLogin, constraints/storage.uniformBucketLevelAccess, constraints/compute.restrictVpcPeering. Start in dry-run mode. Use folder-level exceptions for specific projects. Review and update policies quarterly.',
    tags: ['gcp', 'organization', 'policies', 'governance', 'security'],
  },
  {
    id: 'GCP-026',
    title: 'Cloud Deploy',
    domain: 'gcp',
    content: 'Cloud Deploy is a managed continuous delivery service for GKE and Cloud Run. Define delivery pipelines with sequential targets (dev, staging, prod). Supports canary and standard deployment strategies. Approval gates between stages. Rollback to previous releases. Integrates with Cloud Build for CI.',
    bestPractice: 'Use Cloud Deploy for consistent promotion across environments. Set up approval requirements for production deployments. Use canary strategy for critical services. Enable deploy notifications to Pub/Sub. Use Skaffold for local development with the same deployment pipeline. Track deployment frequency and lead time metrics.',
    tags: ['gcp', 'cloud-deploy', 'ci-cd', 'deployment', 'delivery'],
  },
  {
    id: 'GCP-027',
    title: 'Firestore',
    domain: 'gcp',
    content: 'Firestore is a serverless NoSQL document database. Two modes: Native (real-time sync, offline support, for mobile/web) and Datastore mode (server-side, backward compatible). Auto-scaling, strong consistency, multi-region replication. Document model with collections, documents, and subcollections. Real-time listeners for live updates.',
    bestPractice: 'Use Native mode for new projects. Design data model around your queries (denormalize). Use composite indexes for complex queries. Avoid large documents (1MB limit). Use batch writes for multiple updates. Implement security rules for client-side access. Monitor read/write/delete operations for cost control.',
    tags: ['gcp', 'firestore', 'nosql', 'database', 'serverless', 'document'],
  },
  {
    id: 'GCP-028',
    title: 'Dataflow (Apache Beam)',
    domain: 'gcp',
    content: 'Dataflow is a fully managed service for batch and streaming data processing using Apache Beam SDK. Auto-scales workers based on pipeline demand. Supports Java, Python, Go. Features: exactly-once processing, windowing (fixed, sliding, session), watermarks, side inputs, stateful processing. Integrates with Pub/Sub, BigQuery, Cloud Storage, Bigtable.',
    bestPractice: 'Use Streaming Engine for streaming pipelines (reduces worker cost). Use FlexRS for batch pipelines (Spot VMs, up to 40% savings). Monitor pipeline with Cloud Monitoring metrics. Use Dataflow Prime for right-sizing. Choose between Dataflow and BigQuery: use Dataflow for complex transforms, BigQuery for SQL-expressible transforms. Set appropriate max_num_workers.',
    tags: ['gcp', 'dataflow', 'apache-beam', 'streaming', 'batch', 'etl', 'data-pipeline'],
  },
  {
    id: 'GCP-029',
    title: 'Dataproc (Spark/Hadoop)',
    domain: 'gcp',
    content: 'Dataproc is managed Apache Spark, Hadoop, Flink, and Presto. Create clusters in ~90 seconds. Supports autoscaling, preemptible/Spot workers, and Dataproc Serverless (no cluster management). Integrates with Cloud Storage (HDFS replacement), BigQuery, and Metastore. Component gateway for Jupyter, Spark UI access.',
    bestPractice: 'Use Dataproc Serverless for ad-hoc Spark jobs (no cluster management). Use ephemeral clusters: create, run, delete. Store data in Cloud Storage, not HDFS. Use autoscaling policies for variable workloads. Use Spot VMs for secondary workers. Enable component gateway for web UIs. Consider Dataproc on GKE for Kubernetes-native workflows.',
    tags: ['gcp', 'dataproc', 'spark', 'hadoop', 'big-data', 'analytics'],
  },
  {
    id: 'GCP-030',
    title: 'Cloud Tasks',
    domain: 'gcp',
    content: 'Cloud Tasks manages distributed task execution with guaranteed delivery. HTTP and App Engine targets. Features: rate limiting, retry with exponential backoff, deduplication, scheduling (up to 30 days), task routing. Use for: async processing, background jobs, rate-limited API calls, delayed execution.',
    bestPractice: 'Use Cloud Tasks over Pub/Sub when you need: rate limiting, scheduled delivery, task deduplication, or HTTP target delivery. Set appropriate retry config (max_attempts, min/max_backoff). Use unique task IDs for deduplication. Monitor queue depth and dispatch rate. Use Cloud Tasks + Cloud Run for scalable async processing. Set dispatch rate based on downstream capacity.',
    tags: ['gcp', 'cloud-tasks', 'queue', 'async', 'background-jobs', 'rate-limiting'],
  },
  {
    id: 'GCP-031',
    title: 'Cloud Scheduler',
    domain: 'gcp',
    content: 'Cloud Scheduler is a fully managed cron job scheduler. Targets: HTTP/S endpoints, Pub/Sub topics, App Engine. Supports any cron expression (unix-cron format). Features: timezone support, retry config, OAuth/OIDC authentication for targets, pausing/resuming jobs. Minimum interval: 1 minute.',
    bestPractice: 'Use with Cloud Tasks or Pub/Sub for reliable job execution. Always set a retry policy. Use OIDC tokens for authenticating to Cloud Run/Functions. Set appropriate timezone (not UTC if business-logic dependent). Combine with Cloud Run for serverless cron: Scheduler triggers Run endpoint. Monitor job execution with Cloud Logging.',
    tags: ['gcp', 'cloud-scheduler', 'cron', 'scheduling', 'jobs', 'automation'],
  },
  {
    id: 'GCP-032',
    title: 'Bigtable',
    domain: 'gcp',
    content: 'Cloud Bigtable is a high-performance NoSQL wide-column database. Handles billions of rows, millions of columns. Single-digit millisecond latency at any scale. Use for: time-series, IoT, analytics, ML feature stores. Supports HBase API compatibility. Auto-scales nodes. Replication for HA across zones/regions.',
    bestPractice: 'Design row keys to distribute writes evenly (avoid hotspots). Use reverse timestamps for time-series data. Use column family design: group related columns. Start with 3 nodes minimum for production. Use SSD storage for latency-sensitive, HDD for cost-sensitive. Monitor hottest row key patterns. Use Key Visualizer to detect hotspots.',
    tags: ['gcp', 'bigtable', 'nosql', 'wide-column', 'time-series', 'iot'],
  },
  {
    id: 'GCP-033',
    title: 'Vertex AI',
    domain: 'gcp',
    content: 'Vertex AI is GCP unified ML platform. Features: AutoML (no-code ML for tabular, image, text, video), custom training (TensorFlow, PyTorch, XGBoost, scikit-learn), Model Garden (foundation models including Gemini), Feature Store, Model Registry, Pipelines (Kubeflow-based), Prediction (online/batch), Experiments tracking.',
    bestPractice: 'Start with AutoML for rapid prototyping. Use Vertex AI Workbench (managed JupyterLab) for development. Use Pipelines for reproducible ML workflows. Enable model monitoring for data drift detection. Use Feature Store for consistent feature serving. Use Vertex AI Endpoints with traffic splitting for A/B testing models. Consider Vertex AI Search and Conversation for RAG applications.',
    tags: ['gcp', 'vertex-ai', 'ml', 'machine-learning', 'automl', 'ai', 'gemini'],
  },
  {
    id: 'GCP-034',
    title: 'Cloud KMS (Key Management)',
    domain: 'gcp',
    content: 'Cloud KMS manages cryptographic keys for encryption. Key hierarchy: KeyRing > CryptoKey > CryptoKeyVersion. Protection levels: SOFTWARE, HSM (FIPS 140-2 Level 3), EXTERNAL (EKM). Features: automatic key rotation, key versioning, asymmetric keys (sign/verify), IAM-based access control. CMEK (Customer-Managed Encryption Keys) for services like BigQuery, Cloud Storage, GKE.',
    bestPractice: 'Use CMEK for regulated workloads (specify your own keys). Enable automatic key rotation (90 days recommended). Use separate key rings per environment. Grant roles/cloudkms.cryptoKeyEncrypterDecrypter only where needed. Use HSM keys for compliance requirements. Monitor key usage with Cloud Audit Logs. Never use symmetric key material outside KMS.',
    tags: ['gcp', 'kms', 'encryption', 'security', 'keys', 'cmek', 'hsm'],
  },
  {
    id: 'GCP-035',
    title: 'Security Command Center',
    domain: 'gcp',
    content: 'Security Command Center (SCC) is GCP security and risk management platform. Tiers: Standard (free, basic findings) and Premium (vulnerability scanning, threat detection, compliance). Features: Security Health Analytics (misconfigurations), Web Security Scanner, Event Threat Detection (log-based), Container Threat Detection, Virtual Machine Threat Detection.',
    bestPractice: 'Enable Premium tier for production organizations. Review Security Health Analytics findings weekly. Set up notification configs for critical findings (Pub/Sub, email). Use compliance dashboards for CIS, PCI-DSS, NIST. Integrate findings with SIEM. Enable Container Threat Detection for GKE. Set up mute rules for accepted risks.',
    tags: ['gcp', 'scc', 'security', 'threat-detection', 'compliance', 'vulnerability'],
  },
  {
    id: 'GCP-036',
    title: 'App Engine',
    domain: 'gcp',
    content: 'App Engine is GCP PaaS for web applications. Two environments: Standard (sandboxed runtimes, scales to zero, fast scaling, limited languages) and Flexible (custom Docker containers, any language, minimum 1 instance). Features: automatic scaling, traffic splitting, versioning, built-in services (Memcache, Task Queue, Cron). Standard supports: Python, Java, Node.js, Go, PHP, Ruby.',
    bestPractice: 'Use Standard for simple web apps that need scale-to-zero. Use Flexible only when you need custom runtimes or native dependencies. Prefer Cloud Run for new projects (more flexible). Use traffic splitting for canary deployments. Set warmup requests to reduce cold start latency. Use app.yaml for configuration. Use dispatch.yaml for routing to microservices.',
    tags: ['gcp', 'app-engine', 'paas', 'serverless', 'web', 'hosting'],
  },
  {
    id: 'GCP-037',
    title: 'gcloud CLI Patterns',
    domain: 'gcp',
    content: 'gcloud is the GCP command-line tool. Key commands: gcloud compute (VMs), gcloud container (GKE), gcloud run (Cloud Run), gcloud sql (Cloud SQL), gcloud functions (Cloud Functions), gcloud builds (Cloud Build). Config: gcloud config set project, gcloud config configurations (named profiles). Auth: gcloud auth login, gcloud auth application-default login, gcloud auth activate-service-account.',
    bestPractice: 'Use named configurations for multiple projects: gcloud config configurations create dev. Use --format=json for scripting. Use --filter for server-side filtering. Use gcloud auth application-default for local development (ADC). Never use service account keys — use Workload Identity or ADC. Use gcloud components update regularly. Use gcloud beta/alpha for preview features.',
    tags: ['gcp', 'gcloud', 'cli', 'command-line', 'tooling', 'automation'],
  },
  {
    id: 'GCP-038',
    title: 'AlloyDB',
    domain: 'gcp',
    content: 'AlloyDB is a fully managed PostgreSQL-compatible database with up to 4x faster transactional and 100x faster analytical performance than standard PostgreSQL. Uses intelligent caching and columnar engine. Features: HA with 99.99% SLA, cross-region replication, automated backups, ML-powered query optimization via AlloyDB AI (pgvector built-in).',
    bestPractice: 'Use AlloyDB over Cloud SQL when you need: higher performance, built-in analytics (columnar engine), or pgvector for AI workloads. Use read pool instances for analytics (columnar engine). Enable automatic vacuuming. Use AlloyDB Auth Proxy for connections. Use AlloyDB AI for embedding generation directly in SQL. Start with primary + 1 read pool for most workloads.',
    tags: ['gcp', 'alloydb', 'postgresql', 'database', 'analytics', 'ai', 'pgvector'],
  },
  {
    id: 'GCP-039',
    title: 'VPC Service Controls',
    domain: 'gcp',
    content: 'VPC Service Controls create security perimeters around GCP resources to prevent data exfiltration. Define a perimeter that restricts API access to services like BigQuery, Cloud Storage, Cloud SQL. Features: access levels (IP, device, identity), ingress/egress rules, dry-run mode, bridge perimeters for cross-perimeter communication.',
    bestPractice: 'Start with dry-run mode to identify violations before enforcing. Create perimeters per environment (dev/staging/prod). Use ingress rules for CI/CD access. Use egress rules sparingly. Combine with Organization Policies. Monitor violations in Cloud Audit Logs. Use Access Context Manager for context-aware access levels.',
    tags: ['gcp', 'vpc-service-controls', 'security', 'perimeter', 'data-exfiltration', 'compliance'],
  },
  {
    id: 'GCP-040',
    title: 'Cloud Interconnect and VPN',
    domain: 'gcp',
    content: 'Cloud Interconnect provides dedicated or partner connections to GCP (10/100 Gbps). Dedicated Interconnect for high-bandwidth, consistent needs. Partner Interconnect through service providers (50 Mbps - 50 Gbps). Cloud VPN: HA VPN (99.99% SLA, dual tunnels) and Classic VPN. Cloud Router for BGP dynamic routing.',
    bestPractice: 'Use HA VPN for most hybrid setups (simpler, dual tunnels for HA). Use Dedicated Interconnect for >10 Gbps consistent needs. Always use Cloud Router for dynamic routing over static routes. Configure HA VPN with two tunnels to different Cloud VPN gateways. Use MACsec encryption on Dedicated Interconnect for in-transit encryption.',
    tags: ['gcp', 'interconnect', 'vpn', 'hybrid', 'networking', 'connectivity'],
  },
  {
    id: 'GCP-041',
    title: 'Multi-Region Architecture Patterns',
    domain: 'gcp',
    content: 'GCP multi-region patterns: Active-Active (global LB, Spanner/Firestore), Active-Passive (primary region + DR region), Warm Standby (scaled-down secondary). Key services: Global HTTP(S) LB (anycast), Spanner (multi-region), Cloud Storage (multi-region/dual-region), GKE Multi-Cluster Ingress, Cloud DNS routing policies (geo, failover).',
    bestPractice: 'Use Global HTTP(S) LB for automatic geographic routing. Use Spanner for globally consistent database. Use multi-region Cloud Storage for >99.99% durability. Define RPO/RTO requirements before choosing pattern. Use GKE Multi-Cluster Services for cross-region Kubernetes. Automate failover with Cloud DNS routing policies. Test DR procedures quarterly.',
    tags: ['gcp', 'multi-region', 'disaster-recovery', 'high-availability', 'architecture', 'global'],
  },
  {
    id: 'GCP-042',
    title: 'Quota Management',
    domain: 'gcp',
    content: 'GCP enforces quotas at project, region, and API level. Types: rate quotas (requests/sec), allocation quotas (resource counts/sizes). View quotas in Cloud Console > IAM & Admin > Quotas. Request increases via Cloud Console or gcloud services quota update. Some quotas auto-increase with usage. Monitor quota usage with Cloud Monitoring.',
    bestPractice: 'Monitor quota usage proactively — set alerts at 80% consumption. Request quota increases before scaling events (allow 2-3 business days). Use per-project quotas to prevent runaway resources. Export quota metrics to dashboards. Use Terraform google_project_service to enable APIs. Check regional quotas when deploying to new regions.',
    tags: ['gcp', 'quotas', 'limits', 'resource-management', 'scaling', 'billing'],
  },
];
