'use strict';

module.exports = [
  {
    id: 'AZURE-001',
    title: 'AKS (Azure Kubernetes Service)',
    domain: 'cloud-azure',
    content: 'AKS is managed Kubernetes on Azure. Free control plane. Node pools: System (required, runs system pods) and User (application workloads). Features: Azure CNI networking, Azure AD integration, virtual nodes (ACI for burst), KEDA-based autoscaling, Azure Policy, Defender for Containers. Supports Windows and Linux nodes.',
    bestPractice: 'Use separate system and user node pools. Enable Azure AD RBAC integration. Use managed identity (not service principal). Enable Defender for Containers for security scanning. Use Azure CNI Overlay for better IP management. Enable cluster autoscaler. Use Workload Identity for pod-level Azure access.',
    tags: ['azure', 'aks', 'kubernetes', 'containers', 'managed'],
  },
  {
    id: 'AZURE-002',
    title: 'Azure App Service',
    domain: 'cloud-azure',
    content: 'App Service is Azure PaaS for web apps. Supports .NET, Java, Node.js, Python, PHP, Ruby, custom containers. Features: deployment slots (staging/production swap), auto-scale, custom domains, managed SSL, VNet integration, hybrid connections. App Service Plans define compute resources (Free, Shared, Basic, Standard, Premium, Isolated).',
    bestPractice: 'Use deployment slots for zero-downtime deployments (swap staging to production). Enable auto-scale on Premium plans. Use VNet integration for database access. Enable Always On to prevent cold starts. Use managed identity for Azure resource access. Set up health check path for monitoring.',
    tags: ['azure', 'app-service', 'paas', 'web-apps', 'deployment'],
  },
  {
    id: 'AZURE-003',
    title: 'Azure SQL Database',
    domain: 'cloud-azure',
    content: 'Azure SQL Database is managed SQL Server. Purchase models: DTU (bundled compute, I/O, storage) and vCore (separate compute/storage, more flexible). Tiers: Basic/Standard/Premium (DTU), General Purpose/Business Critical/Hyperscale (vCore). Features: automatic tuning, intelligent insights, geo-replication, auto-failover groups, elastic pools (share resources across databases).',
    bestPractice: 'Use vCore model for production (more control). Use elastic pools when you have many databases with varying loads. Enable automatic tuning and intelligent insights. Set up geo-replication for disaster recovery. Use private endpoints for network security. Enable Azure Defender for SQL threat detection.',
    tags: ['azure', 'sql', 'database', 'managed', 'sql-server'],
  },
  {
    id: 'AZURE-004',
    title: 'Azure Blob Storage',
    domain: 'cloud-azure',
    content: 'Blob Storage is Azure object storage. Access tiers: Hot (frequent access), Cool (30-day min, infrequent), Cold (90-day min), Archive (180-day min, offline). Account types: Standard (HDD-backed) and Premium (SSD-backed). Features: lifecycle management, versioning, soft delete, immutable storage, static website hosting, Azure CDN integration.',
    bestPractice: 'Use lifecycle management to transition blobs between tiers. Enable soft delete for data recovery (14+ days). Use private endpoints for secure access. Enable versioning for critical data. Use SAS tokens (not account keys) for temporary access. Use Azure CDN for static content distribution.',
    tags: ['azure', 'blob', 'storage', 'object-storage', 'tiers'],
  },
  {
    id: 'AZURE-005',
    title: 'Azure Active Directory (Entra ID)',
    domain: 'cloud-azure',
    content: 'Azure AD (now Microsoft Entra ID) provides identity management. Features: single sign-on (SSO), multi-factor authentication (MFA), conditional access policies, Privileged Identity Management (PIM, just-in-time access), application registrations, managed identities for Azure resources. Integrates with Office 365, Azure services, and thousands of SaaS apps.',
    bestPractice: 'Enable MFA for all users (Security Defaults as minimum). Use Conditional Access policies for risk-based authentication. Use PIM for admin roles (just-in-time, time-limited). Use managed identities for Azure service-to-service auth. Disable legacy authentication protocols. Monitor sign-in logs for anomalies.',
    tags: ['azure', 'ad', 'entra', 'identity', 'authentication', 'security'],
  },
  {
    id: 'AZURE-006',
    title: 'Azure Functions',
    domain: 'cloud-azure',
    content: 'Azure Functions is serverless compute. Hosting plans: Consumption (scale to zero, 5-min timeout), Premium (pre-warmed, VNet, 60-min timeout), Dedicated (App Service Plan). Triggers: HTTP, timer, queue, blob, Event Grid, Cosmos DB, Service Bus. Supports: .NET, Java, Python, Node.js, PowerShell, custom handlers.',
    bestPractice: 'Use Consumption plan for bursty workloads. Use Premium plan for consistent latency (pre-warmed instances). Use Durable Functions for stateful workflows. Bind to managed identity for Azure resource access. Use application insights for monitoring. Keep functions small and focused.',
    tags: ['azure', 'functions', 'serverless', 'faas', 'event-driven'],
  },
  {
    id: 'AZURE-007',
    title: 'Azure Virtual Networks (VNet)',
    domain: 'cloud-azure',
    content: 'VNets provide network isolation in Azure. Regional scope. Subnets segment the VNet. NSGs (Network Security Groups) filter traffic at subnet or NIC level. VNet peering connects VNets (same or cross-region). Service Endpoints and Private Endpoints for secure PaaS access. VPN Gateway and ExpressRoute for on-premises connectivity.',
    bestPractice: 'Plan address spaces to avoid overlaps (needed for peering). Use NSGs on subnets (not NICs). Use Private Endpoints for PaaS services (SQL, Storage, Key Vault). Create separate subnets for: app, data, management. Use Azure Bastion instead of public IPs for VM access. Enable VNet flow logs for security analysis.',
    tags: ['azure', 'vnet', 'networking', 'subnets', 'security'],
  },
  {
    id: 'AZURE-008',
    title: 'Azure NSGs (Network Security Groups)',
    domain: 'cloud-azure',
    content: 'NSGs filter network traffic with inbound and outbound rules. Rules: priority (100-4096, lower = first), source, destination, port, protocol, action (allow/deny). Default rules allow VNet-to-VNet and outbound internet. NSGs can be applied to subnets (recommended) or individual NICs. Application Security Groups (ASG) for logical grouping.',
    bestPractice: 'Apply NSGs to subnets, not individual NICs. Use ASGs to group VMs by role (web, app, data). Never open RDP (3389) or SSH (22) to 0.0.0.0/0. Use Azure Bastion for VM access. Enable NSG flow logs for security auditing. Use service tags (AzureCloud, Internet, VirtualNetwork) for simplified rules.',
    tags: ['azure', 'nsg', 'security', 'firewall', 'networking', 'rules'],
  },
  {
    id: 'AZURE-009',
    title: 'Azure DevOps',
    domain: 'cloud-azure',
    content: 'Azure DevOps provides: Boards (work tracking), Repos (Git repos), Pipelines (CI/CD), Test Plans, Artifacts (package feeds). Pipelines: YAML-based (recommended) or classic editor. Supports multi-stage pipelines with environments, approvals, and service connections. Self-hosted or Microsoft-hosted agents. Free for open source (10 parallel jobs).',
    bestPractice: 'Use YAML pipelines for version-controlled CI/CD. Use templates for reusable pipeline components. Set up environments with approval gates for production. Use variable groups and Azure Key Vault integration for secrets. Use service connections with managed identity. Enable branch policies (PR reviews, build validation).',
    tags: ['azure', 'devops', 'ci-cd', 'pipelines', 'git'],
  },
  {
    id: 'AZURE-010',
    title: 'Azure Container Instances (ACI)',
    domain: 'cloud-azure',
    content: 'ACI runs containers without managing VMs. Per-second billing. Use for: burst workloads from AKS (virtual nodes), batch jobs, CI/CD build agents, dev/test environments. Features: container groups (multi-container pods), VNet deployment, GPU support, persistent volumes (Azure Files). Max: 4 vCPU, 16GB memory per container.',
    bestPractice: 'Use for short-lived or burst workloads. Use container groups for sidecar patterns. Deploy to VNet for private access. Use managed identity for Azure resource access. Set restart policy (Always, OnFailure, Never) based on use case. Use ACI for AKS virtual nodes burst scaling.',
    tags: ['azure', 'aci', 'containers', 'serverless', 'burst'],
  },
  {
    id: 'AZURE-011',
    title: 'Azure Monitor',
    domain: 'cloud-azure',
    content: 'Azure Monitor collects and analyzes telemetry. Components: Metrics (numerical data), Logs (structured/unstructured data in Log Analytics), Application Insights (APM), Alerts, Workbooks (visualization). Log Analytics workspace uses Kusto Query Language (KQL). Application Insights provides request tracking, dependency mapping, and live metrics.',
    bestPractice: 'Enable Application Insights for all web applications. Use KQL for log analysis. Set up action groups for alert routing (email, SMS, webhook, Logic Apps). Create workbooks for team dashboards. Use diagnostic settings to send resource logs to Log Analytics. Monitor costs (log ingestion can be expensive).',
    tags: ['azure', 'monitor', 'logging', 'metrics', 'observability', 'application-insights'],
  },
  {
    id: 'AZURE-012',
    title: 'Azure Key Vault',
    domain: 'cloud-azure',
    content: 'Key Vault stores secrets, keys, and certificates. Features: access policies or RBAC, soft delete and purge protection, HSM-backed keys, automatic certificate renewal, integration with App Service, Functions, AKS, and DevOps. Pricing: Standard (software-protected) and Premium (HSM-protected).',
    bestPractice: 'Use RBAC over access policies (more granular). Enable soft delete and purge protection. Use managed identity for access from Azure services. Reference Key Vault secrets in App Service/Functions configuration. Use separate Key Vaults per environment. Enable diagnostic logging for audit trail.',
    tags: ['azure', 'key-vault', 'secrets', 'encryption', 'security', 'certificates'],
  },
  {
    id: 'AZURE-013',
    title: 'Azure Application Gateway',
    domain: 'cloud-azure',
    content: 'Application Gateway is a L7 load balancer with WAF. Features: SSL termination, URL-based routing, multi-site hosting, WebSocket support, autoscaling (v2), connection draining, custom health probes. WAF with OWASP Core Rule Set. WAF policies with exclusions and custom rules. Integrates with AKS via AGIC (Application Gateway Ingress Controller).',
    bestPractice: 'Use Application Gateway v2 (auto-scaling, zone-redundant). Enable WAF in Prevention mode with OWASP 3.2 rules. Use custom health probes matching your application health endpoint. Set connection draining timeout (30s). Use AGIC for AKS integration. Enable diagnostic logs for debugging.',
    tags: ['azure', 'app-gateway', 'load-balancer', 'waf', 'networking'],
  },
  {
    id: 'AZURE-014',
    title: 'Azure Front Door',
    domain: 'cloud-azure',
    content: 'Azure Front Door is a global L7 load balancer with CDN and WAF. Features: global HTTP load balancing, SSL offloading, URL rewriting, caching, WAF, DDoS protection, private link to origins. Routes users to the closest/healthiest backend. Supports weighted routing, priority routing, and session affinity.',
    bestPractice: 'Use Front Door for global applications. Enable caching for static content. Use WAF managed rules for common threats. Set up health probes for backend monitoring. Use Private Link for secure backend connectivity. Combine with Traffic Manager for DNS-level redundancy.',
    tags: ['azure', 'front-door', 'cdn', 'global', 'load-balancer', 'waf'],
  },
  {
    id: 'AZURE-015',
    title: 'Azure Cosmos DB',
    domain: 'cloud-azure',
    content: 'Cosmos DB is a globally distributed multi-model database. APIs: NoSQL (native), MongoDB, Cassandra, Gremlin, Table. Features: single-digit millisecond latency, five consistency levels (strong to eventual), automatic sharding, multi-region writes, serverless and provisioned capacity. SLA: 99.999% availability.',
    bestPractice: 'Choose the right consistency level (Session is default, good for most). Design partition keys for even distribution. Use the serverless tier for dev/low-traffic. Monitor RU consumption and set alerts. Use hierarchical partition keys for multi-tenant. Use change feed for event-driven architectures.',
    tags: ['azure', 'cosmos-db', 'nosql', 'database', 'global', 'multi-model'],
  },
  {
    id: 'AZURE-016',
    title: 'Azure Service Bus',
    domain: 'cloud-azure',
    content: 'Service Bus is enterprise message broker. Features: queues (point-to-point), topics/subscriptions (pub/sub), sessions (ordered processing), dead-letter queue, scheduled messages, message deferral, duplicate detection, auto-forwarding. Tiers: Basic (queues only), Standard, Premium (dedicated resources, VNet).',
    bestPractice: 'Use Premium tier for production (dedicated resources, VNet integration, larger messages). Use sessions for ordered processing. Always configure dead-letter queues. Use duplicate detection for at-most-once delivery. Set lock duration > processing time. Use Service Bus triggers with Azure Functions for event processing.',
    tags: ['azure', 'service-bus', 'messaging', 'queue', 'pubsub', 'enterprise'],
  },
  {
    id: 'AZURE-017',
    title: 'Azure Cache for Redis',
    domain: 'cloud-azure',
    content: 'Managed Redis cache on Azure. Tiers: Basic (no SLA, dev), Standard (replicated, 99.9% SLA), Premium (clustering, persistence, VNet, geo-replication), Enterprise (Redis Enterprise with modules like RediSearch, RedisJSON). Supports Redis 6.x. Features: data persistence (RDB/AOF), clustering (up to 10 shards), geo-replication.',
    bestPractice: 'Use Standard or Premium for production. Enable geo-replication for multi-region. Use clustering for datasets > 6GB. Set maxmemory-policy to allkeys-lru for caching. Use private endpoints for VNet access. Monitor cache hit ratio and memory usage. Use Enterprise tier for advanced Redis modules.',
    tags: ['azure', 'redis', 'cache', 'managed', 'performance'],
  },
  {
    id: 'AZURE-018',
    title: 'Azure Managed Identity',
    domain: 'cloud-azure',
    content: 'Managed Identity provides automatic credential management for Azure services. System-assigned (tied to resource lifecycle) and user-assigned (independent, shareable). Eliminates need for secrets/passwords in code. Supported by: App Service, Functions, VMs, AKS, Container Instances, Logic Apps, and more.',
    bestPractice: 'Use system-assigned identity for single-resource scenarios. Use user-assigned identity when sharing across resources. Never store credentials in code or config. Use DefaultAzureCredential in Azure SDK (auto-detects managed identity). Assign RBAC roles at the most specific scope possible.',
    tags: ['azure', 'managed-identity', 'security', 'authentication', 'credentials'],
  },
  {
    id: 'AZURE-019',
    title: 'Azure Policy',
    domain: 'cloud-azure',
    content: 'Azure Policy enforces organizational standards and assesses compliance. Built-in policies: require tags, restrict regions, enforce encryption, restrict VM sizes. Effects: Deny, Audit, Append, Modify, DeployIfNotExists. Initiatives group related policies. Compliance dashboard shows resource compliance status.',
    bestPractice: 'Start with Audit effect before switching to Deny. Use initiatives for compliance frameworks (CIS, PCI DSS). Assign at management group level for broad coverage. Use DeployIfNotExists for auto-remediation (e.g., enable diagnostic settings). Exempt specific resources when needed. Review compliance weekly.',
    tags: ['azure', 'policy', 'governance', 'compliance', 'security'],
  },
  {
    id: 'AZURE-020',
    title: 'Azure Bastion',
    domain: 'cloud-azure',
    content: 'Azure Bastion provides secure RDP/SSH access to VMs without public IP addresses. Deployed in a dedicated subnet (AzureBastionSubnet). Features: direct browser access from Azure portal, native client support, IP-based connection, shareable links, session recording (Premium). Eliminates need for jump boxes and VPN for VM access.',
    bestPractice: 'Deploy Bastion in a hub VNet peered with spoke VNets. Use Standard or Premium SKU for native client and tunneling. Remove public IPs from VMs after deploying Bastion. Use NSGs on AzureBastionSubnet per documentation. Enable session recording for compliance.',
    tags: ['azure', 'bastion', 'security', 'ssh', 'rdp', 'access'],
  },
  {
    id: 'AZURE-021',
    title: 'Azure Cost Management',
    domain: 'cloud-azure',
    content: 'Azure Cost Management provides cost analysis, budgets, and recommendations. Advisor recommendations for right-sizing, reserved instances, and idle resources. Azure Reservations (1-3 year, up to 72% savings). Azure Hybrid Benefit for Windows Server/SQL Server licenses. Spot VMs for interruptible workloads (up to 90% savings).',
    bestPractice: 'Set up budgets with alerts at 80% and 100%. Use Azure Advisor for cost recommendations weekly. Purchase reservations for steady-state VMs and databases. Use Azure Hybrid Benefit if you have Windows/SQL licenses. Tag all resources for cost allocation. Use auto-shutdown for dev/test VMs.',
    tags: ['azure', 'cost', 'billing', 'optimization', 'reservations', 'budgets'],
  },
  {
    id: 'AZURE-022',
    title: 'Azure Defender (Microsoft Defender for Cloud)',
    domain: 'cloud-azure',
    content: 'Defender for Cloud provides security posture management and threat protection. CSPM (free): Secure Score, compliance assessments, security recommendations. CWP (paid): Defender for Servers, Containers, SQL, Storage, Key Vault, App Service, DNS, Resource Manager. Features: vulnerability scanning, just-in-time VM access, adaptive application controls.',
    bestPractice: 'Enable Defender for Cloud on all subscriptions. Start with free CSPM. Enable paid Defender plans for production workloads. Address high-impact recommendations first (improve Secure Score). Use just-in-time VM access to reduce attack surface. Enable file integrity monitoring on critical servers.',
    tags: ['azure', 'defender', 'security', 'cspm', 'threat-detection'],
  },
  {
    id: 'AZURE-023',
    title: 'Azure Logic Apps',
    domain: 'cloud-azure',
    content: 'Logic Apps is a serverless workflow orchestration service. Visual designer with 400+ connectors (Office 365, Salesforce, SAP, SQL, HTTP). Use for: integration workflows, data transformation, automated approvals, monitoring and alerting pipelines, DevOps automation. Consumption (pay per execution) and Standard (dedicated, VNet) tiers.',
    bestPractice: 'Use for integration scenarios and lightweight automation. Use Standard tier for production (VNet, stateful workflows). Handle failures with retry policies and run-after configurations. Use managed connectors where available. Monitor with Azure Monitor. Use templates for common patterns.',
    tags: ['azure', 'logic-apps', 'automation', 'integration', 'workflow', 'serverless'],
  },
  {
    id: 'AZURE-024',
    title: 'Azure Traffic Manager',
    domain: 'cloud-azure',
    content: 'Traffic Manager is DNS-based global load balancer. Routing methods: Priority (active-passive failover), Weighted (distribute traffic by weight), Performance (route to closest endpoint), Geographic (route by user location), MultiValue (return multiple healthy endpoints), Subnet (route by client IP). Works with any internet-facing endpoint.',
    bestPractice: 'Use Performance routing for latency-sensitive global apps. Use Priority routing for active-passive disaster recovery. Combine with Application Gateway for L7 features. Set appropriate health probe intervals. Use Real User Measurements for accurate latency data. Nest profiles for complex routing scenarios.',
    tags: ['azure', 'traffic-manager', 'dns', 'global', 'load-balancer', 'routing'],
  },
  {
    id: 'AZURE-025',
    title: 'Azure Container Registry (ACR)',
    domain: 'cloud-azure',
    content: 'ACR is managed Docker registry on Azure. Tiers: Basic, Standard, Premium (geo-replication, private endpoints, content trust). Features: ACR Tasks (automated builds on commit/base image update), vulnerability scanning with Defender, Helm chart storage, OCI artifact support, artifact streaming for fast pod startup.',
    bestPractice: 'Use Premium tier for production (geo-replication, private endpoints). Enable Defender vulnerability scanning. Use ACR Tasks for automated builds. Set retention policies for untagged manifests. Use artifact streaming for faster AKS pod startup. Use managed identity for AKS pull access (not admin credentials).',
    tags: ['azure', 'acr', 'docker', 'registry', 'containers'],
  },
];
