'use strict';

module.exports = [
  // PORT ENTRIES
  {
    id: 'PORT-SSH',
    title: 'SSH (Port 22)',
    domain: 'sysadmin',
    port: 22,
    content: 'Secure Shell provides encrypted remote login and command execution. SSH replaces insecure protocols like telnet and rlogin. It supports key-based authentication, port forwarding, and tunneling. The server daemon is typically managed via systemd as sshd.service.',
    bestPractice: 'Disable root login and password authentication in /etc/ssh/sshd_config. Use key-based auth with Ed25519 keys and restrict access via AllowUsers or AllowGroups directives.',
    tags: ['ssh', 'remote', 'security', 'encryption', 'port-22'],
    service: 'sshd',
    aliases: ['openssh', 'sshd'],
  },
  {
    id: 'PORT-FTP',
    title: 'FTP (Port 21)',
    domain: 'sysadmin',
    port: 21,
    content: 'File Transfer Protocol uses port 21 for the control channel and negotiates data connections on separate ports. FTP transmits credentials in cleartext, making it insecure for production use. SFTP (over SSH on port 22) or FTPS (FTP over TLS) are strongly preferred alternatives.',
    bestPractice: 'Avoid plain FTP in production environments. Use SFTP or SCP instead. If FTP is required, enforce TLS with vsftpd or ProFTPD and restrict to passive mode with a defined port range.',
    tags: ['ftp', 'file-transfer', 'legacy', 'port-21'],
    aliases: ['vsftpd', 'proftpd'],
  },
  {
    id: 'PORT-DNS',
    title: 'DNS (Port 53)',
    domain: 'sysadmin',
    port: 53,
    content: 'Domain Name System resolves hostnames to IP addresses using both UDP and TCP on port 53. UDP handles standard queries under 512 bytes, while TCP is used for zone transfers and large responses. DNS is critical infrastructure and its failure causes widespread service outages.',
    bestPractice: 'Run a local caching resolver like systemd-resolved or dnsmasq. Monitor DNS resolution latency and set up secondary nameservers for redundancy.',
    fix: 'If DNS resolution fails, check /etc/resolv.conf for correct nameservers, test with dig or nslookup, and verify firewall rules allow UDP/TCP port 53 outbound.',
    tags: ['dns', 'networking', 'name-resolution', 'port-53'],
    service: 'named',
    aliases: ['bind', 'named', 'unbound', 'dnsmasq'],
  },
  {
    id: 'PORT-HTTP',
    title: 'HTTP (Port 80)',
    domain: 'sysadmin',
    port: 80,
    content: 'Hypertext Transfer Protocol serves unencrypted web traffic on port 80. In modern deployments, port 80 is primarily used to redirect clients to HTTPS on port 443. Web servers like nginx and Apache listen on this port by default.',
    bestPractice: "Always redirect HTTP to HTTPS. Keep port 80 open only for ACME certificate challenges (Let's Encrypt) and 301 redirects to the secure endpoint.",
    tags: ['http', 'web', 'port-80', 'plaintext'],
    aliases: ['www', 'web'],
  },
  {
    id: 'PORT-HTTPS',
    title: 'HTTPS (Port 443)',
    domain: 'sysadmin',
    port: 443,
    content: 'HTTPS provides encrypted HTTP communication via TLS on port 443. All production web traffic should use HTTPS to protect data in transit. Modern TLS 1.3 reduces handshake latency to a single round trip and removes legacy cipher suites.',
    bestPractice: 'Use TLS 1.2+ only, prefer TLS 1.3. Automate certificate renewal with certbot or ACME clients. Set HSTS headers with a long max-age to prevent downgrade attacks.',
    tags: ['https', 'tls', 'ssl', 'web', 'port-443', 'encryption'],
    aliases: ['ssl', 'tls'],
  },
  {
    id: 'PORT-SMTP',
    title: 'SMTP (Port 25)',
    domain: 'sysadmin',
    port: 25,
    content: 'Simple Mail Transfer Protocol on port 25 handles server-to-server email delivery. Many ISPs and cloud providers block outbound port 25 to prevent spam. This port is used for mail relay between MTAs, not for client submission.',
    bestPractice: 'Use port 587 for client submission with authentication. Configure SPF, DKIM, and DMARC records to improve deliverability and prevent spoofing.',
    tags: ['smtp', 'email', 'mail', 'port-25'],
    service: 'postfix',
    aliases: ['postfix', 'sendmail', 'exim', 'mail'],
  },
  {
    id: 'PORT-SMTP-TLS',
    title: 'SMTP Submission TLS (Port 587)',
    domain: 'sysadmin',
    port: 587,
    content: 'Port 587 is the standard mail submission port for email clients sending mail through an SMTP server. It requires authentication (SMTP AUTH) and supports STARTTLS for encryption. This is the correct port for applications and users to send outbound email.',
    bestPractice: 'Require STARTTLS on port 587 and reject plaintext authentication. Use port 465 for implicit TLS if your MTA supports it. Always enforce authentication to prevent open relay abuse.',
    tags: ['smtp', 'email', 'tls', 'submission', 'port-587'],
    aliases: ['submission'],
  },
  {
    id: 'PORT-POP3',
    title: 'POP3 (Port 110)',
    domain: 'sysadmin',
    port: 110,
    content: 'Post Office Protocol version 3 allows email clients to download messages from a mail server. POP3 typically removes messages from the server after download, making it unsuitable for multi-device access. The encrypted variant POP3S runs on port 995.',
    bestPractice: 'Prefer IMAP over POP3 for multi-device support. If POP3 is required, enforce TLS via STARTTLS or use POP3S on port 995.',
    tags: ['pop3', 'email', 'mail', 'port-110'],
    aliases: ['pop', 'pop3s'],
  },
  {
    id: 'PORT-IMAP',
    title: 'IMAP (Port 143)',
    domain: 'sysadmin',
    port: 143,
    content: 'Internet Message Access Protocol keeps email on the server and synchronizes state across multiple clients. IMAP supports folders, flags, and server-side search. The encrypted variant IMAPS runs on port 993 and should be used for all production deployments.',
    bestPractice: 'Enforce TLS via STARTTLS on port 143 or use IMAPS on port 993 exclusively. Set mailbox quotas to prevent storage exhaustion on the mail server.',
    tags: ['imap', 'email', 'mail', 'port-143'],
    service: 'dovecot',
    aliases: ['dovecot', 'imaps'],
  },
  {
    id: 'PORT-MYSQL',
    title: 'MySQL (Port 3306)',
    domain: 'sysadmin',
    port: 3306,
    content: 'MySQL and MariaDB listen on port 3306 for client connections by default. This port should never be exposed to the public internet. Use unix sockets for local connections and SSH tunnels or VPN for remote database access.',
    bestPractice: 'Bind MySQL to 127.0.0.1 or a private network interface. Use mysql_secure_installation after initial setup. Enable the slow query log and set long_query_time to identify performance issues.',
    fix: 'If connections are refused, check bind-address in /etc/mysql/my.cnf, verify the service is running with systemctl status mysql, and confirm firewall rules allow access from the client IP.',
    tags: ['mysql', 'database', 'mariadb', 'port-3306'],
    service: 'mysql',
    aliases: ['mariadb', 'mysqld'],
  },
  {
    id: 'PORT-POSTGRESQL',
    title: 'PostgreSQL (Port 5432)',
    domain: 'sysadmin',
    port: 5432,
    content: 'PostgreSQL listens on port 5432 for client connections. Access control is managed through pg_hba.conf, which defines authentication methods per client, database, and user. PostgreSQL supports SSL/TLS connections natively for encrypted transport.',
    bestPractice: 'Restrict listen_addresses in postgresql.conf to specific interfaces. Use scram-sha-256 authentication in pg_hba.conf instead of md5 or trust. Enable SSL and require it for remote connections.',
    fix: 'Connection refused errors typically mean PostgreSQL is not listening on the expected interface. Check listen_addresses in postgresql.conf and client auth rules in pg_hba.conf, then reload with pg_ctl reload.',
    tags: ['postgresql', 'postgres', 'database', 'port-5432'],
    service: 'postgresql',
    aliases: ['postgres', 'pg', 'psql'],
  },
  {
    id: 'PORT-REDIS',
    title: 'Redis (Port 6379)',
    domain: 'sysadmin',
    port: 6379,
    content: 'Redis is an in-memory key-value store listening on port 6379. By default, Redis has no authentication and binds to all interfaces, which is a severe security risk. Unauthorized Redis access has been widely exploited to gain server root access via SSH key injection.',
    bestPractice: 'Always set a strong password with requirepass. Bind to 127.0.0.1 unless remote access is needed. Rename or disable dangerous commands like FLUSHALL, CONFIG, and DEBUG in production.',
    fix: 'If Redis is unresponsive, check memory usage with redis-cli INFO memory. Redis may have hit maxmemory and its eviction policy may be rejecting writes. Review maxmemory-policy setting.',
    tags: ['redis', 'cache', 'in-memory', 'port-6379'],
    service: 'redis',
    aliases: ['redis-server', 'redis-cli'],
  },
  {
    id: 'PORT-MONGODB',
    title: 'MongoDB (Port 27017)',
    domain: 'sysadmin',
    port: 27017,
    content: 'MongoDB listens on port 27017 for client connections. Historically, MongoDB shipped with no authentication enabled, leading to thousands of exposed databases on the internet. Modern versions enable auth by default, but verification is still essential.',
    bestPractice: 'Enable authentication and create dedicated users per database with minimum required roles. Bind to specific interfaces via bindIp. Enable TLS for all connections and use x.509 certificates for inter-node auth in replica sets.',
    tags: ['mongodb', 'nosql', 'database', 'port-27017'],
    service: 'mongodb',
    aliases: ['mongod', 'mongo', 'mongosh'],
  },
  {
    id: 'PORT-ELASTICSEARCH',
    title: 'Elasticsearch (Port 9200)',
    domain: 'sysadmin',
    port: 9200,
    content: 'Elasticsearch exposes its REST API on port 9200 for indexing and search operations, and uses port 9300 for inter-node cluster communication. Without authentication, anyone with network access can read, modify, or delete all data via simple HTTP requests.',
    bestPractice: 'Enable Elasticsearch Security (formerly X-Pack) for authentication and TLS. Never expose port 9200 to the public internet. Set network.host to a private interface and use a reverse proxy for controlled access.',
    tags: ['elasticsearch', 'search', 'elk', 'port-9200'],
    service: 'elasticsearch',
    aliases: ['es', 'elastic', 'elk'],
  },
  {
    id: 'PORT-PROMETHEUS',
    title: 'Prometheus (Port 9090)',
    domain: 'sysadmin',
    port: 9090,
    content: 'Prometheus is a pull-based metrics collection system with its web UI and API on port 9090. It scrapes /metrics endpoints on configured targets at regular intervals. Prometheus stores time-series data locally and supports PromQL for powerful metric queries.',
    bestPractice: 'Place Prometheus behind a reverse proxy with authentication since it has no built-in auth. Set appropriate retention periods with --storage.tsdb.retention.time. Use recording rules for frequently queried expensive expressions.',
    tags: ['prometheus', 'monitoring', 'metrics', 'port-9090'],
    service: 'prometheus',
  },
  {
    id: 'PORT-GRAFANA',
    title: 'Grafana (Port 3000)',
    domain: 'sysadmin',
    port: 3000,
    content: 'Grafana serves its dashboard UI on port 3000 by default. It connects to data sources like Prometheus, Elasticsearch, and InfluxDB to visualize metrics. The default admin credentials are admin/admin, which must be changed immediately on first login.',
    bestPractice: 'Change default admin password immediately. Configure OAuth or LDAP for user authentication. Use provisioning files in /etc/grafana/provisioning/ for dashboards-as-code. Disable user registration in production.',
    fix: 'If Grafana shows no data on dashboards, verify the data source connection in Configuration > Data Sources. Check that the time range selector matches when data was collected and that Prometheus is scraping targets correctly.',
    tags: ['grafana', 'monitoring', 'dashboards', 'visualization', 'port-3000'],
    service: 'grafana',
    aliases: ['grafana-server'],
  },
  {
    id: 'PORT-RABBITMQ',
    title: 'RabbitMQ (Port 5672)',
    domain: 'sysadmin',
    port: 5672,
    content: 'RabbitMQ uses port 5672 for AMQP protocol connections and port 15672 for its management web UI. It provides reliable message queuing with support for multiple messaging patterns including pub/sub, work queues, and RPC. Messages can be persisted to disk for durability.',
    bestPractice: 'Delete the default guest user or restrict it to localhost only. Create separate vhosts per application with dedicated users. Enable the management plugin for monitoring and set up queue TTLs and max-length policies to prevent unbounded growth.',
    tags: ['rabbitmq', 'amqp', 'messaging', 'queue', 'port-5672'],
    service: 'rabbitmq',
    aliases: ['rabbitmq-server', 'amqp'],
  },
  {
    id: 'PORT-KAFKA',
    title: 'Kafka (Port 9092)',
    domain: 'sysadmin',
    port: 9092,
    content: 'Apache Kafka brokers listen on port 9092 for producer and consumer connections. Kafka is a distributed event streaming platform that stores messages in partitioned, replicated topics. It depends on ZooKeeper (port 2181) or KRaft mode for cluster coordination.',
    bestPractice: 'Use KRaft mode instead of ZooKeeper for new deployments. Set replication factor to at least 3 and min.insync.replicas to 2 for durability. Monitor consumer group lag with kafka-consumer-groups.sh to detect slow consumers.',
    tags: ['kafka', 'streaming', 'messaging', 'port-9092'],
    aliases: ['kafka-server', 'kafka-broker'],
  },
  {
    id: 'PORT-DOCKER-API',
    title: 'Docker API (Port 2376)',
    domain: 'sysadmin',
    port: 2376,
    content: 'The Docker daemon API listens on port 2376 with TLS (2375 without TLS). Exposing the Docker API without TLS is equivalent to giving root access to anyone on the network, since Docker can mount the host filesystem and run privileged containers.',
    bestPractice: 'Never expose port 2375 (unencrypted Docker API). If remote Docker access is needed, use TLS mutual authentication on port 2376 with client certificates. Prefer SSH-based Docker contexts over TCP socket exposure.',
    fix: 'If you have accidentally exposed port 2375, immediately stop the Docker daemon, check for unauthorized containers with docker ps -a, and audit for SSH keys injected into /root/.ssh/authorized_keys.',
    tags: ['docker', 'api', 'security', 'port-2376'],
    aliases: ['dockerd'],
  },
  {
    id: 'PORT-K8S-API',
    title: 'Kubernetes API Server (Port 6443)',
    domain: 'sysadmin',
    port: 6443,
    content: 'The Kubernetes API server listens on port 6443 for all cluster management operations. Every kubectl command, controller, and scheduler communicates through this endpoint. It handles authentication, authorization (RBAC), and admission control for all API requests.',
    bestPractice: 'Restrict API server access to trusted networks using firewall rules. Enable audit logging to track all API requests. Use RBAC with least-privilege service accounts and never grant cluster-admin to application workloads.',
    tags: ['kubernetes', 'k8s', 'api', 'port-6443', 'orchestration'],
    aliases: ['kube-apiserver', 'k8s-api'],
  },
  {
    id: 'PORT-ETCD',
    title: 'etcd (Port 2379)',
    domain: 'sysadmin',
    port: 2379,
    content: 'etcd is a distributed key-value store that serves as the backbone of Kubernetes cluster state on port 2379 for client traffic and 2380 for peer communication. It stores all cluster configuration, secrets, and resource definitions. Losing etcd data means losing the entire cluster state.',
    bestPractice: 'Always run etcd with TLS enabled for both client and peer communication. Take regular snapshots with etcdctl snapshot save. Run etcd on dedicated SSDs since it is highly sensitive to disk I/O latency.',
    fix: 'If etcd is slow or unresponsive, check disk fsync latency with fio. etcd requires under 10ms fsync for reliable operation. Move etcd data to SSD storage if on spinning disks.',
    tags: ['etcd', 'kubernetes', 'k8s', 'key-value', 'port-2379'],
    aliases: ['etcdctl'],
  },
  {
    id: 'PORT-MEMCACHED',
    title: 'Memcached (Port 11211)',
    domain: 'sysadmin',
    port: 11211,
    content: 'Memcached is a high-performance in-memory caching system listening on port 11211. It uses a simple key-value protocol with no authentication by default. Memcached has been exploited in massive DDoS amplification attacks when exposed to the internet via UDP.',
    bestPractice: 'Bind memcached to 127.0.0.1 or a private interface only. Disable UDP with -U 0 to prevent amplification attacks. Set a memory limit with -m to prevent OOM kills. Use SASL authentication if remote access is required.',
    fix: 'If memcached is consuming too much memory or causing OOM kills, lower the -m flag value and review cache eviction stats with the stats and stats slabs commands.',
    tags: ['memcached', 'cache', 'in-memory', 'port-11211'],
    aliases: ['memcache'],
  },

  // HTTP STATUS CODE ENTRIES
  {
    id: 'HTTP-200',
    title: 'HTTP 200 OK',
    domain: 'sysadmin',
    httpCode: 200,
    content: 'The request succeeded and the server returned the requested resource. This is the standard response for successful GET requests. For POST requests, it indicates the action was completed and the response body contains the result.',
    tags: ['http', 'status-code', 'success', '2xx'],
  },
  {
    id: 'HTTP-201',
    title: 'HTTP 201 Created',
    domain: 'sysadmin',
    httpCode: 201,
    content: 'The request succeeded and a new resource was created as a result. This is the appropriate response for successful POST requests that create entities. The response should include a Location header pointing to the newly created resource.',
    tags: ['http', 'status-code', 'success', '2xx', 'rest'],
  },
  {
    id: 'HTTP-204',
    title: 'HTTP 204 No Content',
    domain: 'sysadmin',
    httpCode: 204,
    content: 'The request succeeded but there is no content to return in the response body. Commonly used for successful DELETE requests or PUT updates where no response body is needed. The client should not navigate away from the current page.',
    tags: ['http', 'status-code', 'success', '2xx', 'rest'],
  },
  {
    id: 'HTTP-301',
    title: 'HTTP 301 Moved Permanently',
    domain: 'sysadmin',
    httpCode: 301,
    content: 'The requested resource has been permanently moved to a new URL specified in the Location header. Browsers and search engines will cache this redirect and update their references. Use this for permanent URL changes like HTTP to HTTPS redirects or domain migrations.',
    bestPractice: 'Use 301 for permanent URL changes to preserve SEO value. Browsers cache 301s aggressively, so use 302 during testing. Verify redirect chains are minimal to avoid performance degradation.',
    tags: ['http', 'status-code', 'redirect', '3xx', 'seo'],
  },
  {
    id: 'HTTP-302',
    title: 'HTTP 302 Found (Temporary Redirect)',
    domain: 'sysadmin',
    httpCode: 302,
    content: 'The requested resource is temporarily located at a different URL. Unlike 301, browsers and search engines should continue using the original URL for future requests. Commonly used for login redirects and temporary maintenance pages.',
    tags: ['http', 'status-code', 'redirect', '3xx'],
  },
  {
    id: 'HTTP-304',
    title: 'HTTP 304 Not Modified',
    domain: 'sysadmin',
    httpCode: 304,
    content: 'The resource has not been modified since the last request, so the client can use its cached version. The server responds with 304 when the client sends If-Modified-Since or If-None-Match headers that match the current resource. No response body is sent, saving bandwidth.',
    bestPractice: 'Set proper ETag and Last-Modified headers to enable 304 responses. This significantly reduces bandwidth and improves page load times for returning visitors.',
    tags: ['http', 'status-code', 'cache', '3xx', 'performance'],
  },
  {
    id: 'HTTP-400',
    title: 'HTTP 400 Bad Request',
    domain: 'sysadmin',
    httpCode: 400,
    content: 'The server cannot process the request due to malformed syntax, invalid parameters, or missing required fields. This is a client-side error indicating the request itself is wrong. Common causes include invalid JSON, missing Content-Type headers, or exceeding size limits.',
    fix: 'Check request body format matches Content-Type header. Validate JSON syntax and ensure required fields are present. Review API documentation for parameter constraints and encoding requirements.',
    tags: ['http', 'status-code', 'error', '4xx', 'client-error'],
  },
  {
    id: 'HTTP-401',
    title: 'HTTP 401 Unauthorized',
    domain: 'sysadmin',
    httpCode: 401,
    content: 'The request lacks valid authentication credentials. Despite the name, this code means unauthenticated rather than unauthorized (which is 403). The response must include a WWW-Authenticate header indicating the accepted authentication scheme.',
    fix: 'Verify the Authorization header is present and correctly formatted. Check that API keys or tokens have not expired. For Bearer tokens, ensure the token is properly base64-encoded and not malformed.',
    tags: ['http', 'status-code', 'error', '4xx', 'auth', 'security'],
  },
  {
    id: 'HTTP-403',
    title: 'HTTP 403 Forbidden',
    domain: 'sysadmin',
    httpCode: 403,
    content: 'The server understood the request but refuses to authorize it. Unlike 401, re-authenticating will not help because the client lacks sufficient permissions. This is used when the user is authenticated but does not have access rights to the requested resource.',
    fix: 'Check file permissions on the server (chmod/chown). Verify the user role has the required permissions. For web servers, review directory access rules and .htaccess files. Check SELinux or AppArmor contexts if enabled.',
    tags: ['http', 'status-code', 'error', '4xx', 'auth', 'permissions'],
  },
  {
    id: 'HTTP-404',
    title: 'HTTP 404 Not Found',
    domain: 'sysadmin',
    httpCode: 404,
    content: 'The server cannot find the requested resource. This may indicate the URL is wrong, the resource was deleted, or the routing configuration is missing a handler. In REST APIs, it means the specific entity identified by the URL does not exist.',
    fix: 'Verify the URL path and check for typos. Review web server configuration and routing rules. For nginx, check location blocks and try_files directives. For application servers, verify route registrations.',
    tags: ['http', 'status-code', 'error', '4xx', 'routing'],
  },
  {
    id: 'HTTP-408',
    title: 'HTTP 408 Request Timeout',
    domain: 'sysadmin',
    httpCode: 408,
    content: 'The server timed out waiting for the client to send a complete request. This differs from 504 which is a gateway timeout. The client took too long to transmit the request body or headers. Some servers send this to close idle keep-alive connections.',
    fix: 'Increase client_body_timeout and client_header_timeout in nginx, or Timeout in Apache. Check for network latency issues between client and server. For file uploads, increase timeouts proportionally to expected upload sizes.',
    tags: ['http', 'status-code', 'error', '4xx', 'timeout'],
  },
  {
    id: 'HTTP-429',
    title: 'HTTP 429 Too Many Requests',
    domain: 'sysadmin',
    httpCode: 429,
    content: 'The client has sent too many requests in a given time window and is being rate-limited. The response should include a Retry-After header indicating how long to wait before making new requests. This protects servers from abuse and ensures fair resource allocation.',
    fix: 'Implement exponential backoff in client code. Respect the Retry-After header value. On the server side, tune rate limit thresholds in nginx (limit_req), API gateways, or application middleware.',
    bestPractice: 'Return Retry-After header with seconds until the limit resets. Use sliding window or token bucket algorithms for smooth rate limiting. Apply different limits per API key or user tier.',
    tags: ['http', 'status-code', 'error', '4xx', 'rate-limit', 'throttling'],
  },
  {
    id: 'HTTP-500',
    title: 'HTTP 500 Internal Server Error',
    domain: 'sysadmin',
    httpCode: 500,
    content: 'A generic server-side error indicating the application encountered an unexpected condition. This often points to unhandled exceptions, misconfigured backends, or programming errors. The server should log the detailed error internally and return a generic message to the client.',
    fix: 'Check application logs for the full stack trace. Review recent deployments for regressions. Common causes include database connection failures, null pointer exceptions, and misconfigured environment variables.',
    tags: ['http', 'status-code', 'error', '5xx', 'server-error'],
  },
  {
    id: 'HTTP-502',
    title: 'HTTP 502 Bad Gateway',
    domain: 'sysadmin',
    httpCode: 502,
    content: 'The reverse proxy or load balancer received an invalid response from the upstream server. This typically means the backend application crashed, returned malformed headers, or the upstream connection was reset. Common with nginx proxying to Node.js, Python, or PHP-FPM backends.',
    fix: 'Check if the upstream application is running and healthy. Review upstream error logs. Verify proxy_pass URL in nginx matches the backend listen address. Increase proxy_buffer_size if the upstream sends large headers.',
    tags: ['http', 'status-code', 'error', '5xx', 'proxy', 'gateway'],
  },
  {
    id: 'HTTP-503',
    title: 'HTTP 503 Service Unavailable',
    domain: 'sysadmin',
    httpCode: 503,
    content: 'The server is temporarily unable to handle requests, usually due to overload or maintenance. Unlike 500, this implies the condition is temporary and the client should retry later. Load balancers return 503 when all backend instances are unhealthy.',
    fix: 'Check system resources (CPU, memory, disk). Verify backend services are running. Review connection pool exhaustion in databases or application servers. During planned maintenance, return a Retry-After header.',
    tags: ['http', 'status-code', 'error', '5xx', 'availability', 'overload'],
  },
  {
    id: 'HTTP-504',
    title: 'HTTP 504 Gateway Timeout',
    domain: 'sysadmin',
    httpCode: 504,
    content: 'The reverse proxy or gateway did not receive a timely response from the upstream server. This indicates the backend took too long to process the request. Common during database-heavy operations, external API calls, or when the upstream is under heavy load.',
    fix: 'Increase proxy_read_timeout in nginx or ProxyTimeout in Apache. Optimize slow upstream queries or add request timeouts in application code. Consider moving long-running operations to background workers with job queues.',
    tags: ['http', 'status-code', 'error', '5xx', 'timeout', 'proxy'],
  },

  // SERVICE ENTRIES
  {
    id: 'SVC-NGINX',
    title: 'nginx Web Server',
    domain: 'sysadmin',
    service: 'nginx',
    content: 'nginx is an event-driven web server and reverse proxy known for high concurrency with low memory usage. It handles static files, load balancing, SSL termination, and caching. Configuration is organized in server blocks within /etc/nginx/nginx.conf and /etc/nginx/sites-enabled/.',
    bestPractice: 'Use separate server blocks per domain in sites-available with symlinks to sites-enabled. Test configuration with nginx -t before reloading. Enable gzip compression and configure worker_processes auto to match CPU cores.',
    fix: 'If nginx fails to start, run nginx -t to check for syntax errors. Common issues include duplicate listen directives, missing SSL certificates, and incorrect file permissions on log directories.',
    tags: ['nginx', 'web-server', 'reverse-proxy', 'load-balancer'],
    aliases: ['nginx-server'],
  },
  {
    id: 'SVC-APACHE',
    title: 'Apache HTTP Server',
    domain: 'sysadmin',
    service: 'apache',
    content: 'Apache httpd is a process/thread-based web server using the prefork or event MPM. Configuration lives in /etc/apache2/ (Debian) or /etc/httpd/ (RHEL). It supports .htaccess files for per-directory config, mod_rewrite for URL manipulation, and mod_proxy for reverse proxying.',
    bestPractice: 'Use the event MPM instead of prefork for better performance. Disable .htaccess lookups with AllowOverride None in production for speed. Enable mod_security as a web application firewall.',
    fix: 'If Apache returns permission errors, check file ownership matches the www-data or apache user. Verify SELinux contexts with ls -Z and fix with restorecon -Rv /var/www/.',
    tags: ['apache', 'httpd', 'web-server'],
    aliases: ['httpd', 'apache2'],
  },
  {
    id: 'SVC-SYSTEMD',
    title: 'systemd Init System',
    domain: 'sysadmin',
    service: 'systemd',
    content: 'systemd is the init system and service manager for most modern Linux distributions. It manages service lifecycle, dependencies, logging (journald), device management (udevd), and login sessions (logind). Unit files in /etc/systemd/system/ override vendor defaults in /usr/lib/systemd/system/.',
    bestPractice: 'Create override files with systemctl edit instead of modifying vendor unit files directly. Use Type=notify for services that signal readiness. Set Restart=on-failure and RestartSec=5s for automatic recovery. Define resource limits with MemoryMax and CPUQuota.',
    tags: ['systemd', 'init', 'service-manager', 'linux'],
    aliases: ['init', 'systemctl'],
  },
  {
    id: 'SVC-DOCKER',
    title: 'Docker Container Runtime',
    domain: 'sysadmin',
    service: 'docker',
    content: 'Docker provides OS-level virtualization using containers. The Docker daemon (dockerd) manages container lifecycle, images, volumes, and networks. Docker uses overlay2 as its default storage driver and iptables for container networking. Configuration is stored in /etc/docker/daemon.json.',
    bestPractice: 'Configure log rotation in daemon.json to prevent disk exhaustion. Use user namespaces for additional isolation. Set default-ulimits and storage-driver options. Prune unused images and volumes regularly with docker system prune.',
    fix: 'If Docker fails to start, check journalctl -u docker for errors. Common issues include missing kernel modules (overlay), exhausted disk space, or conflicting iptables rules.',
    tags: ['docker', 'containers', 'runtime'],
    aliases: ['dockerd', 'containerd', 'docker-engine'],
  },
  {
    id: 'SVC-POSTGRESQL',
    title: 'PostgreSQL Database Service',
    domain: 'sysadmin',
    service: 'postgresql',
    content: 'PostgreSQL is an advanced open-source relational database. Key configuration files are postgresql.conf for server settings and pg_hba.conf for client authentication. It supports MVCC, table partitioning, logical replication, and rich indexing options including GiST and GIN.',
    bestPractice: 'Tune shared_buffers to 25% of system RAM, effective_cache_size to 75%, and work_mem based on connection count. Use pgBouncer for connection pooling. Enable pg_stat_statements to identify slow queries. Schedule regular VACUUM ANALYZE.',
    tags: ['postgresql', 'database', 'rdbms'],
    aliases: ['postgres', 'pg'],
  },
  {
    id: 'SVC-MYSQL',
    title: 'MySQL Database Service',
    domain: 'sysadmin',
    service: 'mysql',
    content: 'MySQL is a widely-used relational database. Key configuration is in /etc/mysql/my.cnf or /etc/my.cnf. The InnoDB storage engine provides ACID compliance, row-level locking, and crash recovery. MySQL supports primary-replica replication and Group Replication for high availability.',
    bestPractice: 'Set innodb_buffer_pool_size to 70-80% of available RAM on dedicated servers. Enable the slow query log with long_query_time=1. Use the performance_schema for deep diagnostics. Run mysql_secure_installation on new instances.',
    tags: ['mysql', 'database', 'rdbms'],
    aliases: ['mysqld', 'mariadb'],
  },
  {
    id: 'SVC-REDIS',
    title: 'Redis In-Memory Store',
    domain: 'sysadmin',
    service: 'redis',
    content: 'Redis is an in-memory data structure store used as a cache, message broker, and database. It supports strings, hashes, lists, sets, sorted sets, and streams. Persistence options include RDB snapshots and AOF (append-only file) logging. Redis Sentinel provides automatic failover.',
    bestPractice: 'Set maxmemory and choose an appropriate eviction policy (allkeys-lru for caches). Enable AOF with appendfsync everysec for durability. Monitor memory fragmentation ratio and restart Redis if it exceeds 1.5.',
    tags: ['redis', 'cache', 'in-memory', 'data-store'],
    aliases: ['redis-server'],
  },
  {
    id: 'SVC-MONGODB',
    title: 'MongoDB Document Store',
    domain: 'sysadmin',
    service: 'mongodb',
    content: 'MongoDB is a document-oriented NoSQL database storing data as BSON documents. It supports replica sets for high availability and sharding for horizontal scaling. The WiredTiger storage engine provides document-level concurrency control and compression.',
    bestPractice: 'Always run replica sets with at least 3 members, even in single-server deployments. Create indexes to support query patterns and use explain() to verify index usage. Set appropriate write concern and read preference for your consistency requirements.',
    tags: ['mongodb', 'nosql', 'document-store'],
    aliases: ['mongod', 'mongosh'],
  },
  {
    id: 'SVC-ELASTICSEARCH',
    title: 'Elasticsearch Search Engine',
    domain: 'sysadmin',
    service: 'elasticsearch',
    content: 'Elasticsearch is a distributed search and analytics engine built on Apache Lucene. It stores data in indices composed of shards distributed across cluster nodes. Configuration is in /etc/elasticsearch/elasticsearch.yml. JVM heap settings are critical for performance.',
    bestPractice: 'Set JVM heap to 50% of available RAM but never exceed 31GB to benefit from compressed oops. Disable swapping with bootstrap.memory_lock. Use index lifecycle management (ILM) to automatically roll over and delete old indices.',
    fix: 'If Elasticsearch is slow, check heap pressure with _nodes/stats. High garbage collection times indicate heap is too small. Bulk indexing can starve search threads, so use separate thread pools.',
    tags: ['elasticsearch', 'search', 'elk', 'lucene'],
    aliases: ['es', 'elastic'],
  },
  {
    id: 'SVC-PROMETHEUS',
    title: 'Prometheus Monitoring',
    domain: 'sysadmin',
    service: 'prometheus',
    content: 'Prometheus is a time-series database and monitoring system that pulls metrics from instrumented targets via HTTP. It uses PromQL for querying and supports alerting rules that fire to Alertmanager. Configuration is in prometheus.yml with scrape configs, rules, and alert destinations.',
    bestPractice: 'Use service discovery (Kubernetes, Consul, or file-based) instead of static target lists. Create recording rules for expensive queries used in dashboards. Set up Alertmanager with deduplication and routing to appropriate notification channels.',
    tags: ['prometheus', 'monitoring', 'metrics', 'alerting'],
  },
  {
    id: 'SVC-GRAFANA',
    title: 'Grafana Dashboard Platform',
    domain: 'sysadmin',
    service: 'grafana',
    content: 'Grafana is a multi-platform visualization and analytics tool that connects to various data sources including Prometheus, InfluxDB, and Elasticsearch. Dashboards are stored in its internal SQLite or external PostgreSQL/MySQL database. Configuration is in /etc/grafana/grafana.ini.',
    bestPractice: 'Use provisioning for dashboards and data sources to enable infrastructure-as-code workflows. Set up organizations and teams for multi-tenant environments. Configure an external database (PostgreSQL) for production instead of the default SQLite.',
    tags: ['grafana', 'visualization', 'dashboards', 'monitoring'],
    aliases: ['grafana-server'],
  },

  // LINUX COMMANDS AND CONCEPTS
  {
    id: 'CMD-TOP-HTOP',
    title: 'top and htop - Process Monitoring',
    domain: 'sysadmin',
    content: 'top displays real-time system resource usage including CPU, memory, and per-process statistics. htop is an improved interactive version with color output, mouse support, and tree view. Key metrics to watch are load average, CPU steal time (st), and memory usage excluding buffers/cache.',
    bestPractice: 'Use htop with tree view (F5) to see process hierarchies. Sort by memory (M) or CPU (P) to find resource hogs. Check load average relative to CPU count: load greater than CPU count indicates saturation.',
    tags: ['top', 'htop', 'process', 'monitoring', 'cpu', 'memory'],
  },
  {
    id: 'CMD-DF-DU',
    title: 'df and du - Disk Usage Analysis',
    domain: 'sysadmin',
    content: 'df (disk free) shows filesystem-level disk usage and mount points. du (disk usage) calculates space used by files and directories. Use df -h for human-readable filesystem overview and du -sh /path/* | sort -rh to find the largest directories.',
    fix: 'If df shows a filesystem is full but du shows less usage, deleted files may still be held open by running processes. Use lsof +D /mount | grep deleted to find them, then restart the offending process to release the space.',
    tags: ['df', 'du', 'disk', 'storage', 'filesystem'],
  },
  {
    id: 'CMD-FREE',
    title: 'free - Memory Usage',
    domain: 'sysadmin',
    content: 'free displays total, used, free, shared, and cached memory. The available column is the best indicator of how much memory can be allocated without swapping. Linux aggressively uses free RAM for disk caching, so used memory alone is misleading.',
    bestPractice: 'Use free -h for human-readable output. Monitor the available column, not free. If available memory is consistently below 10-15% of total, consider adding RAM or reducing workload. Check buff/cache to understand how much memory is reclaimable.',
    tags: ['free', 'memory', 'ram', 'swap', 'monitoring'],
  },
  {
    id: 'CMD-PS-KILL',
    title: 'ps and kill - Process Management',
    domain: 'sysadmin',
    content: 'ps displays information about running processes. Common invocations are ps aux (BSD style, all users) and ps -ef (System V style). kill sends signals to processes: SIGTERM (15) for graceful shutdown, SIGKILL (9) for forced termination, and SIGHUP (1) for reload.',
    bestPractice: 'Always try SIGTERM before SIGKILL to allow processes to clean up gracefully. Use pkill or killall to target processes by name. Use ps auxf for tree view to understand parent-child relationships.',
    tags: ['ps', 'kill', 'process', 'signals', 'management'],
  },
  {
    id: 'CMD-LSOF',
    title: 'lsof - List Open Files',
    domain: 'sysadmin',
    content: 'lsof lists all open files, which in Linux includes regular files, directories, sockets, pipes, and devices. Use lsof -i :PORT to find which process is using a port, lsof -u USER to list files opened by a user, and lsof +D /path to find processes using files in a directory.',
    fix: 'If a port is already in use, run lsof -i :PORT to identify the process. If a filesystem will not unmount, use lsof +D /mount to find processes with open files on that mount, then stop them before unmounting.',
    tags: ['lsof', 'files', 'sockets', 'ports', 'debugging'],
  },
  {
    id: 'CMD-SS-NETSTAT',
    title: 'ss and netstat - Network Socket Statistics',
    domain: 'sysadmin',
    content: 'ss (socket statistics) is the modern replacement for netstat, providing faster output from kernel data structures. Use ss -tlnp to list all TCP listening sockets with process names, ss -s for a summary of socket states, and ss -tnp state established to see active connections.',
    bestPractice: 'Use ss instead of netstat on modern systems as netstat is deprecated in many distributions. Monitor TIME_WAIT socket counts with ss -s, as excessive TIME_WAIT states can exhaust port ranges and cause connection failures.',
    tags: ['ss', 'netstat', 'networking', 'sockets', 'tcp'],
  },
  {
    id: 'CMD-TCPDUMP',
    title: 'tcpdump - Network Packet Capture',
    domain: 'sysadmin',
    content: 'tcpdump captures and displays network packets on an interface. Use tcpdump -i eth0 port 80 to capture HTTP traffic, -w file.pcap to save for Wireshark analysis, and -nn to disable name resolution for faster output. BPF filters allow precise traffic selection.',
    bestPractice: 'Always use -w to write to a pcap file for later analysis in Wireshark. Limit captures with -c count or time-based rotation with -G seconds. Use -s 0 to capture full packets when payload inspection is needed.',
    tags: ['tcpdump', 'networking', 'packet-capture', 'debugging', 'wireshark'],
  },
  {
    id: 'CMD-TRACEROUTE',
    title: 'traceroute - Network Path Discovery',
    domain: 'sysadmin',
    content: 'traceroute maps the network path packets take to reach a destination by sending packets with incrementing TTL values. Each hop responds with an ICMP time exceeded message. Use mtr (My Traceroute) for a continuous, combined ping-and-traceroute display that shows packet loss per hop.',
    fix: 'If traceroute shows asterisks (*) at a hop, that router may be filtering ICMP or deprioritizing it. Try traceroute -T to use TCP SYN packets instead, or use mtr for a more reliable continuous measurement.',
    tags: ['traceroute', 'mtr', 'networking', 'routing', 'diagnostics'],
  },
  {
    id: 'CMD-DIG',
    title: 'dig - DNS Query Tool',
    domain: 'sysadmin',
    content: 'dig (Domain Information Groper) performs DNS lookups and displays detailed responses including query time, authoritative servers, and TTL values. Use dig example.com A for address records, dig example.com MX for mail servers, and dig +trace example.com to follow the full resolution chain from root nameservers.',
    bestPractice: 'Use dig +short for concise output in scripts. Test against specific nameservers with dig @8.8.8.8 domain.com to bypass local caching. Use dig +trace to debug delegation issues in the DNS hierarchy.',
    tags: ['dig', 'dns', 'networking', 'name-resolution', 'debugging'],
    aliases: ['nslookup', 'host'],
  },
  {
    id: 'CMD-IPTABLES-UFW',
    title: 'iptables and ufw - Firewall Management',
    domain: 'sysadmin',
    content: 'iptables is the traditional Linux firewall using chains (INPUT, OUTPUT, FORWARD) and tables (filter, nat, mangle). ufw (Uncomplicated Firewall) is a user-friendly frontend for iptables. nftables is the modern replacement for iptables with a cleaner syntax and better performance.',
    bestPractice: 'Use ufw for simple single-server setups: ufw default deny incoming, ufw allow ssh, ufw enable. For complex rules, use iptables with a saved ruleset via iptables-save/iptables-restore. Always allow SSH before enabling the firewall to avoid lockout.',
    fix: 'If locked out after enabling the firewall, access the server via console (IPMI/KVM/cloud console) and run iptables -F to flush all rules, then reconfigure carefully.',
    tags: ['iptables', 'ufw', 'nftables', 'firewall', 'security', 'networking'],
    aliases: ['nftables', 'firewall'],
  },
  {
    id: 'CMD-JOURNALCTL',
    title: 'journalctl - systemd Log Viewer',
    domain: 'sysadmin',
    content: 'journalctl queries the systemd journal, which collects logs from all systemd services, the kernel, and standard output/error. Use journalctl -u service to filter by unit, -f for live tailing, -p err to filter by priority, and --since for time-based queries.',
    bestPractice: 'Set SystemMaxUse in /etc/systemd/journald.conf to limit journal size. Use journalctl -xe for recent errors with context. Combine filters like journalctl -u nginx -p err --since today to show only recent nginx errors.',
    tags: ['journalctl', 'logging', 'systemd', 'journal', 'debugging'],
  },
  {
    id: 'CMD-SYSTEMCTL',
    title: 'systemctl - Service Management',
    domain: 'sysadmin',
    content: 'systemctl controls the systemd init system and service manager. Core commands: start/stop/restart for immediate control, enable/disable for boot persistence, status for current state and recent logs, and daemon-reload to pick up unit file changes.',
    bestPractice: 'Always run systemctl daemon-reload after modifying unit files. Use systemctl list-units --failed to find broken services. Use systemctl edit for drop-in overrides instead of modifying vendor unit files directly.',
    fix: 'If a service fails to start, run systemctl status service and journalctl -u service -n 50 to see the error. Check ExecStart path exists, the user has permissions, and all After/Requires dependencies are met.',
    tags: ['systemctl', 'systemd', 'service', 'management', 'init'],
  },
  {
    id: 'CMD-CRONTAB',
    title: 'crontab - Scheduled Tasks',
    domain: 'sysadmin',
    content: 'cron executes scheduled commands at specified intervals using the five-field time format: minute, hour, day-of-month, month, day-of-week. Edit user crontabs with crontab -e. System crontabs in /etc/crontab and /etc/cron.d/ include a user field. Output goes to email by default.',
    bestPractice: 'Redirect cron output to a log file with >> /var/log/cron-job.log 2>&1. Use flock -n /tmp/job.lock to prevent overlapping runs. Set PATH and other environment variables at the top of the crontab since cron runs with a minimal environment.',
    fix: 'If a cron job is not running, verify the crontab is loaded with crontab -l. Check that the command uses full paths since cron has a minimal PATH. Review /var/log/syslog or journalctl -u cron for execution logs.',
    tags: ['crontab', 'cron', 'scheduling', 'automation'],
  },
  {
    id: 'CMD-CHMOD-CHOWN',
    title: 'chmod and chown - File Permissions',
    domain: 'sysadmin',
    content: 'chmod changes file permission bits (read=4, write=2, execute=1) and chown changes file ownership. Common patterns: chmod 755 for directories and scripts, chmod 644 for regular files, chmod 600 for private keys. The sticky bit (chmod +t) on /tmp prevents users from deleting other users files.',
    bestPractice: 'Use numeric mode (chmod 644) for precision and symbolic mode (chmod u+x) for targeted changes. Set umask 027 in shell profiles to create files as 640 and directories as 750 by default. Never chmod 777 in production.',
    tags: ['chmod', 'chown', 'permissions', 'security', 'filesystem'],
  },
  {
    id: 'CMD-SWAP',
    title: 'Swap Management',
    domain: 'sysadmin',
    content: 'Swap provides overflow space when physical RAM is exhausted by writing inactive memory pages to disk. Create swap files with fallocate, format with mkswap, and activate with swapon. The vm.swappiness kernel parameter (0-100) controls how aggressively the kernel swaps. Default is 60.',
    bestPractice: 'Set vm.swappiness to 10 for database servers and latency-sensitive workloads. For servers with ample RAM, set it to 1 to swap only as a last resort. Monitor swap usage with free -h and swapon --show. Size swap at 1-2x RAM for systems that hibernate, otherwise 1-4 GB is sufficient.',
    fix: 'To create a swap file: fallocate -l 4G /swapfile, chmod 600 /swapfile, mkswap /swapfile, swapon /swapfile. Add to /etc/fstab for persistence: /swapfile none swap sw 0 0.',
    tags: ['swap', 'memory', 'virtual-memory', 'performance'],
  },
  {
    id: 'CMD-SYSCTL',
    title: 'sysctl - Kernel Parameter Tuning',
    domain: 'sysadmin',
    content: 'sysctl reads and modifies kernel parameters at runtime via the /proc/sys/ interface. Persistent settings go in /etc/sysctl.conf or /etc/sysctl.d/*.conf files. Critical tunables include net.core.somaxconn (listen queue), vm.swappiness (swap behavior), and fs.file-max (open file limit).',
    bestPractice: 'For high-traffic servers, increase net.core.somaxconn to 65535, net.ipv4.tcp_max_syn_backlog to 65535, and fs.file-max to 2097152. Apply changes with sysctl -p. Always test tuning changes in staging before production.',
    tags: ['sysctl', 'kernel', 'tuning', 'performance', 'networking'],
  },
  {
    id: 'CMD-LOGROTATE',
    title: 'logrotate - Log File Rotation',
    domain: 'sysadmin',
    content: 'logrotate automatically rotates, compresses, and removes old log files to prevent disk exhaustion. Configuration is in /etc/logrotate.conf and /etc/logrotate.d/. It supports time-based (daily, weekly) and size-based rotation, with postrotate scripts to signal applications to reopen log files.',
    bestPractice: 'Use copytruncate for applications that cannot reopen log files, but prefer postrotate with signal-based reopening for zero-loss rotation. Set compress and delaycompress to save disk space. Always test configurations with logrotate -d /etc/logrotate.d/myapp for dry-run validation.',
    tags: ['logrotate', 'logging', 'disk', 'maintenance'],
  },
  {
    id: 'CMD-FSTAB',
    title: '/etc/fstab - Filesystem Mount Table',
    domain: 'sysadmin',
    content: '/etc/fstab defines filesystems to mount at boot. Each line specifies the device (UUID recommended), mount point, filesystem type, options, dump flag, and fsck pass number. Errors in fstab can prevent the system from booting, so always validate entries before rebooting.',
    bestPractice: 'Use UUID= or LABEL= instead of device paths like /dev/sda1, which can change between boots. Add nofail option for non-critical mounts to prevent boot failures. Test new entries with mount -a before rebooting.',
    fix: 'If a system fails to boot due to fstab errors, boot into single-user mode or a rescue shell. Remount root as read-write with mount -o remount,rw / then fix /etc/fstab. Remove or comment out the broken entry.',
    tags: ['fstab', 'filesystem', 'mount', 'boot', 'storage'],
  },
  {
    id: 'CMD-LVM',
    title: 'LVM - Logical Volume Management',
    domain: 'sysadmin',
    content: 'LVM provides flexible disk management with three layers: physical volumes (PV), volume groups (VG), and logical volumes (LV). LVM allows resizing volumes without unmounting, spanning multiple disks, and creating snapshots. Commands follow the pattern pv*/vg*/lv* (e.g., pvdisplay, vgextend, lvresize).',
    bestPractice: 'Use LVM for all server installations to enable future resizing. Leave 10-20% of the VG free for snapshots and emergency expansion. Grow logical volumes with lvextend -L +10G /dev/vg/lv followed by resize2fs (ext4) or xfs_growfs (XFS) to expand the filesystem.',
    fix: 'To extend a full logical volume: lvextend -l +100%FREE /dev/vg/lv extends to use all free space. Then resize2fs /dev/vg/lv (ext4) or xfs_growfs /mount (XFS) to expand the filesystem online without downtime.',
    tags: ['lvm', 'storage', 'disk', 'volume', 'partitioning'],
    aliases: ['pvcreate', 'vgcreate', 'lvcreate', 'lvextend'],
  },
];
